<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum BenefitType: string
{
    case Custom = 'custom';
    case Discord = 'discord';
    case GithubRepository = 'github_repository';
    case Downloadables = 'downloadables';
    case LicenseKeys = 'license_keys';
    case MeterCredit = 'meter_credit';
    case FeatureFlag = 'feature_flag';
    case SlackSharedChannel = 'slack_shared_channel';
}
