<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum BenefitVisibility: string
{
    case Draft = 'draft';
    case Private = 'private';
    case Public = 'public';
}
