<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum CheckoutStatus: string
{
    case Open = 'open';
    case Expired = 'expired';
    case Confirmed = 'confirmed';
    case Succeeded = 'succeeded';
    case Failed = 'failed';
}
