<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum CustomerCancellationReason: string
{
    case CustomerService = 'customer_service';
    case LowQuality = 'low_quality';
    case MissingFeatures = 'missing_features';
    case SwitchedService = 'switched_service';
    case TooComplex = 'too_complex';
    case TooExpensive = 'too_expensive';
    case Unused = 'unused';
    case Other = 'other';
}
