<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum DisputeStatus: string
{
    case Prevented = 'prevented';
    case EarlyWarning = 'early_warning';
    case NeedsResponse = 'needs_response';
    case UnderReview = 'under_review';
    case Lost = 'lost';
    case Won = 'won';
}
