<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum FilterConjunction: string
{
    case And = 'and';
    case Or = 'or';
}
