<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum MeterUnit: string
{
    case Scalar = 'scalar';
    case Token = 'token';
    case Custom = 'custom';
}
