<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum MetricType: string
{
    case Scalar = 'scalar';
    case Currency = 'currency';
    case CurrencySubCent = 'currency_sub_cent';
    case Percentage = 'percentage';
}
