<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum OrderBillingReason: string
{
    case Purchase = 'purchase';
    case SubscriptionCreate = 'subscription_create';
    case SubscriptionCycle = 'subscription_cycle';
    case SubscriptionUpdate = 'subscription_update';
    case SubscriptionMeterCycle = 'subscription_meter_cycle';
}
