<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum OrganizationStatus: string
{
    case Created = 'created';
    case Review = 'review';
    case Snoozed = 'snoozed';
    case Denied = 'denied';
    case Active = 'active';
    case Blocked = 'blocked';
    case Offboarding = 'offboarding';
    case Offboarded = 'offboarded';
}
