<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum OrganizationSocialPlatforms: string
{
    case X = 'x';
    case Github = 'github';
    case Facebook = 'facebook';
    case Instagram = 'instagram';
    case Youtube = 'youtube';
    case Tiktok = 'tiktok';
    case Linkedin = 'linkedin';
    case Threads = 'threads';
    case Discord = 'discord';
    case Other = 'other';
}
