<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum ProductSortProperty: string
{
    case CreatedAt = 'created_at';
    case CreatedAtDesc = '-created_at';
    case Name = 'name';
    case NameDesc = '-name';
    case PriceAmountType = 'price_amount_type';
    case PriceAmountTypeDesc = '-price_amount_type';
    case PriceAmount = 'price_amount';
    case PriceAmountDesc = '-price_amount';
}
