<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum ProductPriceSource: string
{
    case Catalog = 'catalog';
    case AdHoc = 'ad_hoc';
}
