<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum RefundCreateReason: string
{
    case Duplicate = 'duplicate';
    case Fraudulent = 'fraudulent';
    case CustomerRequest = 'customer_request';
    case ServiceDisruption = 'service_disruption';
    case SatisfactionGuarantee = 'satisfaction_guarantee';
    case Other = 'other';
}
