<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum SeatTierType: string
{
    case Volume = 'volume';
    case Graduated = 'graduated';
}
