<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum SeatStatus: string
{
    case Pending = 'pending';
    case Claimed = 'claimed';
    case Revoked = 'revoked';
}
