<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Enums;

enum SubscriptionProrationBehavior: string
{
    case Invoice = 'invoice';
    case Prorate = 'prorate';
    case NextPeriod = 'next_period';
    case Reset = 'reset';
}
