<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\CountryAlpha2;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class AddressInput extends PolarData
{
    public function __construct(
        public readonly CountryAlpha2 $country,
        public readonly ?string $line1 = null,
        public readonly ?string $line2 = null,
        public readonly ?string $postalCode = null,
        public readonly ?string $city = null,
        public readonly ?string $state = null,
    ) {}
}
