<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema of a custom field attached to a resource.
 */
#[MapName(SnakeCaseMapper::class)]
class AttachedCustomField extends PolarData
{
    public function __construct(
        /**
         * ID of the custom field.
         */
        public readonly string $customFieldId,
        public readonly CustomField $customField,
        /**
         * Order of the custom field in the resource.
         */
        public readonly int $order,
        /**
         * Whether the value is required for this custom field.
         */
        public readonly bool $required,
    ) {}
}
