<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class BenefitLicenseKeysCreateProperties extends Data
{
    public function __construct(
        public readonly ?string $prefix = null,
        public readonly ?BenefitLicenseKeyExpirationProperties $expires = null,
        public readonly ?BenefitLicenseKeyActivationCreateProperties $activations = null,
        public readonly ?int $limitUsage = null,
    ) {}
}
