<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class BenefitGrantSlackSharedChannelProperties extends Data
{
    public function __construct(
        public readonly ?string $invitedEmail = null,
        public readonly ?string $channelId = null,
        public readonly ?string $channelName = null,
        public readonly ?string $inviteId = null,
        public readonly ?string $inviteUrl = null,
        public readonly ?string $connectedTeamId = null,
    ) {}
}
