<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A benefit of type `custom`.
 *
 * Use it to grant any kind of benefit that doesn't fit in the other types.
 */
#[MapName(SnakeCaseMapper::class)]
class BenefitCustom extends Benefit
{
    public BenefitCustomProperties $properties;
}
