<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Properties for a benefit of type `github_repository`.
 */
#[MapName(SnakeCaseMapper::class)]
class BenefitGitHubRepositoryProperties extends PolarData
{
    public function __construct(
        /**
         * The owner of the repository.
         */
        public readonly string $repositoryOwner,
        /**
         * The name of the repository.
         */
        public readonly string $repositoryName,
        /**
         * The permission level to grant. Read more about roles and their permissions on [GitHub
         * documentation](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role).
         */
        public readonly string $permission,
    ) {}
}
