<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
abstract class BenefitGrantWebhook extends PolarData
{
    /**
     * Creation timestamp of the object.
     */
    public CarbonImmutable $createdAt;

    /**
     * Last modification timestamp of the object.
     */
    public ?CarbonImmutable $modifiedAt;

    /**
     * The ID of the grant.
     */
    public string $id;

    /**
     * Whether the benefit is granted.
     */
    public bool $isGranted;

    /**
     * Whether the benefit is revoked.
     */
    public bool $isRevoked;

    /**
     * The ID of the subscription that granted this benefit.
     */
    public ?string $subscriptionId;

    /**
     * The ID of the order that granted this benefit.
     */
    public ?string $orderId;

    /**
     * The ID of the customer concerned by this grant.
     */
    public string $customerId;

    /**
     * The ID of the benefit concerned by this grant.
     */
    public string $benefitId;

    public Customer $customer;

    /**
     * Build the concrete grant from a webhook payload.
     *
     * Benefit grants are discriminated by the nested benefit's type rather than a
     * top-level field, so they are resolved here instead of through morph().
     *
     * Deliberately not named `from...`: laravel-data treats any static `from*` method as
     * a magical constructor, which would make this call itself forever.
     *
     * @param  array<string, mixed>  $payload
     */
    public static function resolve(array $payload): self
    {
        $benefit = $payload['benefit'] ?? [];
        $type = is_array($benefit) ? ($benefit['type'] ?? null) : null;

        return match ($type) {
            'discord' => BenefitGrantDiscordWebhook::from($payload),
            'github_repository' => BenefitGrantGitHubRepositoryWebhook::from($payload),
            'downloadables' => BenefitGrantDownloadablesWebhook::from($payload),
            'license_keys' => BenefitGrantLicenseKeysWebhook::from($payload),
            'meter_credit' => BenefitGrantMeterCreditWebhook::from($payload),
            'feature_flag' => BenefitGrantFeatureFlagWebhook::from($payload),
            'slack_shared_channel' => BenefitGrantSlackSharedChannelWebhook::from($payload),
            default => BenefitGrantCustomWebhook::from($payload),
        };
    }
}
