<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A benefit of type `feature_flag`.
 *
 * Use it to grant feature flags with key-value metadata
 * that can be queried via the API and webhooks.
 */
#[MapName(SnakeCaseMapper::class)]
class BenefitFeatureFlag extends Benefit
{
    public BenefitFeatureFlagProperties $properties;
}
