<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class BenefitSlackSharedChannelCreateProperties extends PolarData
{
    public function __construct(
        /**
         * Polar Slack integration to use for this benefit.
         */
        public readonly string $slackIntegrationId,
        public readonly string $channelNameTemplate,
        public readonly ?bool $private = null,
        public readonly ?string $welcomeMessage = null,
        public readonly ?bool $archiveOnRevoke = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $teamInvitees = null,
    ) {}
}
