<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Properties for a benefit of type `discord`.
 */
#[MapName(SnakeCaseMapper::class)]
class BenefitDiscordProperties extends Data
{
    public function __construct(
        /**
         * The ID of the Discord server.
         */
        public readonly string $guildId,
        /**
         * The ID of the Discord role to grant.
         */
        public readonly string $roleId,
        /**
         * Whether to kick the member from the Discord server on revocation.
         */
        public readonly bool $kickMember,
        public readonly string $guildToken,
    ) {}
}
