<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class BenefitDownloadablesCreateProperties extends Data
{
    public function __construct(
        /**
         * @var list<string>
         */
        public readonly array $files,
        /**
         * @var array<string, mixed>|null
         */
        public readonly ?array $archived = null,
    ) {}
}
