<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\BenefitType;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class BenefitPublic extends Data
{
    public function __construct(
        /**
         * The ID of the benefit.
         */
        public readonly string $id,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The type of the benefit.
         */
        public readonly BenefitType $type,
        /**
         * The description of the benefit.
         */
        public readonly string $description,
        /**
         * Whether the benefit is selectable when creating a product.
         */
        public readonly bool $selectable,
        /**
         * Whether the benefit is deletable.
         */
        public readonly bool $deletable,
        /**
         * Whether the benefit is deleted.
         */
        public readonly bool $isDeleted,
        /**
         * The ID of the organization owning the benefit.
         */
        public readonly string $organizationId,
    ) {}
}
