<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\BenefitVisibility;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema to create a benefit of type `meter_unit`.
 */
#[MapName(SnakeCaseMapper::class)]
class BenefitMeterCreditCreate extends Data implements BenefitCreate
{
    public function __construct(
        /**
         * The description of the benefit. Will be displayed on products having this benefit.
         */
        public readonly string $description,
        public readonly BenefitMeterCreditCreateProperties $properties,
        /**
         * Key-value object allowing you to store additional information.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $metadata = null,
        public readonly string $type = 'meter_credit',
        /**
         * The ID of the organization owning the benefit. **Required unless you use an organization
         * token.**
         */
        public readonly ?string $organizationId = null,
        /**
         * The visibility of the benefit in the customer portal.
         */
        public readonly ?BenefitVisibility $visibility = null,
    ) {}
}
