<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class BenefitGrantCustomWebhook extends BenefitGrantWebhook
{
    public BenefitCustom $benefit;

    public BenefitGrantCustomProperties $properties;

    /**
     * The timestamp when the benefit was granted. If `None`, the benefit is not granted.
     */
    public ?CarbonImmutable $grantedAt = null;

    /**
     * The timestamp when the benefit was revoked. If `None`, the benefit is not revoked.
     */
    public ?CarbonImmutable $revokedAt = null;

    /**
     * The ID of the member concerned by this grant.
     */
    public ?string $memberId = null;

    /**
     * The error information if the benefit grant failed with an unrecoverable error.
     */
    public ?BenefitGrantError $error = null;

    public ?Member $member = null;

    public ?BenefitGrantCustomProperties $previousProperties = null;
}
