<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class BenefitSlackSharedChannelProperties extends Data
{
    public function __construct(
        /**
         * Polar Slack integration linked to this benefit.
         */
        public readonly string $slackIntegrationId,
        /**
         * Template for the channel name. Supports placeholders: {customer_name},
         * {customer_email_local}, and {metadata.<key>} for any value stored in customer user metadata.
         */
        public readonly string $channelNameTemplate,
        /**
         * Create the channel as private (recommended).
         */
        public readonly ?bool $private = null,
        /**
         * Optional message posted to the channel right after creation.
         */
        public readonly ?string $welcomeMessage = null,
        /**
         * Archive the channel when the benefit is revoked.
         */
        public readonly ?bool $archiveOnRevoke = null,
        /**
         * Slack user IDs from the merchant workspace to invite to every channel created for this
         * benefit.
         *
         * @var list<string>|null
         */
        public readonly ?array $teamInvitees = null,
    ) {}
}
