<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Properties for creating a benefit of type `meter_unit`.
 */
#[MapName(SnakeCaseMapper::class)]
class BenefitMeterCreditCreateProperties extends Data
{
    public function __construct(
        public readonly int $units,
        public readonly bool $rollover,
        public readonly string $meterId,
    ) {}
}
