<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\BenefitVisibility;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Attributes\PropertyForMorph;
use Spatie\LaravelData\Contracts\PropertyMorphableData;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
abstract class Benefit extends Data implements PropertyMorphableData
{
    /**
     * The ID of the benefit.
     */
    public string $id;

    /**
     * Creation timestamp of the object.
     */
    public CarbonImmutable $createdAt;

    /**
     * Last modification timestamp of the object.
     */
    public ?CarbonImmutable $modifiedAt;

    #[PropertyForMorph]
    public string $type;

    /**
     * The description of the benefit.
     */
    public string $description;

    /**
     * Whether the benefit is selectable when creating a product.
     */
    public bool $selectable;

    /**
     * Whether the benefit is deletable.
     */
    public bool $deletable;

    /**
     * Whether the benefit is deleted.
     */
    public bool $isDeleted;

    /**
     * The ID of the organization owning the benefit.
     */
    public string $organizationId;

    /**
     * @var array<string, mixed>
     */
    public array $metadata;

    /**
     * The visibility of the benefit in the customer portal.
     */
    public BenefitVisibility $visibility;

    public bool $visibilityConfigurable;

    public static function morph(array $properties): ?string
    {
        return match ($properties['type']) {
            'custom' => BenefitCustom::class,
            'discord' => BenefitDiscord::class,
            'downloadables' => BenefitDownloadables::class,
            'feature_flag' => BenefitFeatureFlag::class,
            'github_repository' => BenefitGitHubRepository::class,
            'license_keys' => BenefitLicenseKeys::class,
            'meter_credit' => BenefitMeterCredit::class,
            'slack_shared_channel' => BenefitSlackSharedChannel::class,
            default => null,
        };
    }
}
