<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class BenefitGrant extends Data
{
    public function __construct(
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the grant.
         */
        public readonly string $id,
        /**
         * Whether the benefit is granted.
         */
        public readonly bool $isGranted,
        /**
         * Whether the benefit is revoked.
         */
        public readonly bool $isRevoked,
        /**
         * The ID of the subscription that granted this benefit.
         */
        public readonly ?string $subscriptionId,
        /**
         * The ID of the order that granted this benefit.
         */
        public readonly ?string $orderId,
        /**
         * The ID of the customer concerned by this grant.
         */
        public readonly string $customerId,
        /**
         * The ID of the benefit concerned by this grant.
         */
        public readonly string $benefitId,
        public readonly Customer $customer,
        public readonly Benefit $benefit,
        /**
         * @var BenefitGrantDiscordProperties|BenefitGrantGitHubRepositoryProperties|BenefitGrantDownloadablesProperties|BenefitGrantLicenseKeysProperties|BenefitGrantCustomProperties|BenefitGrantFeatureFlagProperties|BenefitGrantSlackSharedChannelProperties
         */
        public readonly BenefitGrantDiscordProperties|BenefitGrantGitHubRepositoryProperties|BenefitGrantDownloadablesProperties|BenefitGrantLicenseKeysProperties|BenefitGrantCustomProperties|BenefitGrantFeatureFlagProperties|BenefitGrantSlackSharedChannelProperties $properties,
        /**
         * The timestamp when the benefit was granted. If `None`, the benefit is not granted.
         */
        public readonly ?CarbonImmutable $grantedAt = null,
        /**
         * The timestamp when the benefit was revoked. If `None`, the benefit is not revoked.
         */
        public readonly ?CarbonImmutable $revokedAt = null,
        /**
         * The ID of the member concerned by this grant.
         */
        public readonly ?string $memberId = null,
        /**
         * The error information if the benefit grant failed with an unrecoverable error.
         */
        public readonly ?BenefitGrantError $error = null,
        public readonly ?Member $member = null,
    ) {}
}
