<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Properties for a benefit of type `meter_unit`.
 */
#[MapName(SnakeCaseMapper::class)]
class BenefitMeterCreditProperties extends PolarData
{
    public function __construct(
        public readonly int $units,
        public readonly bool $rollover,
        public readonly string $meterId,
    ) {}
}
