<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class BenefitDiscordUpdate extends PolarData
{
    public function __construct(
        /**
         * Key-value object allowing you to store additional information.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $metadata = null,
        /**
         * The description of the benefit. Will be displayed on products having this benefit.
         */
        public readonly ?string $description = null,
        public readonly string $type = 'discord',
        public readonly ?BenefitDiscordCreateProperties $properties = null,
    ) {}
}
