<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A benefit of type `meter_unit`.
 *
 * Use it to grant a number of units on a specific meter.
 */
#[MapName(SnakeCaseMapper::class)]
class BenefitMeterCredit extends Benefit
{
    public BenefitMeterCreditProperties $properties;
}
