<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A benefit of type `discord`.
 *
 * Use it to automatically invite your backers to a Discord server.
 */
#[MapName(SnakeCaseMapper::class)]
class BenefitDiscord extends Benefit
{
    public BenefitDiscordProperties $properties;
}
