<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\CheckoutStatus;
use Danestves\LaravelPolar\Enums\PaymentProcessor;
use Danestves\LaravelPolar\Enums\TaxBehavior;
use Danestves\LaravelPolar\Enums\TrialInterval;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Checkout session data retrieved using an access token.
 */
#[MapName(SnakeCaseMapper::class)]
class Checkout extends Data
{
    public function __construct(
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * Payment processor used.
         */
        public readonly PaymentProcessor $paymentProcessor,
        /**
         * Status of the checkout session.
         *
         *         - Open: the checkout session was opened.
         *         - Expired: the checkout session was expired and is no more accessible.
         *         - Confirmed: the user on the checkout session clicked Pay. This is not indicative of
         * the payment's success status.
         *         - Failed: the checkout definitely failed for technical reasons and cannot be
         * retried. In most cases, this state is never reached.
         *         - Succeeded: the payment on the checkout was performed successfully.
         */
        public readonly CheckoutStatus $status,
        /**
         * Client secret used to update and complete the checkout session from the client.
         */
        public readonly string $clientSecret,
        /**
         * URL where the customer can access the checkout session.
         */
        public readonly string $url,
        /**
         * Expiration date and time of the checkout session.
         */
        public readonly CarbonImmutable $expiresAt,
        /**
         * URL where the customer will be redirected after a successful payment.
         */
        public readonly string $successUrl,
        /**
         * When set, a back button will be shown in the checkout to return to this URL.
         */
        public readonly ?string $returnUrl,
        /**
         * When checkout is embedded, represents the Origin of the page embedding the checkout. Used as
         * a security measure to send messages only to the embedding page.
         */
        public readonly ?string $embedOrigin,
        /**
         * Amount in cents, before discounts and taxes.
         */
        public readonly int $amount,
        /**
         * Discount amount in cents.
         */
        public readonly int $discountAmount,
        /**
         * Amount in cents, after discounts but before taxes.
         */
        public readonly int $netAmount,
        /**
         * Sales tax amount in cents. If `null`, it means there is no enough information yet to
         * calculate it.
         */
        public readonly ?int $taxAmount,
        /**
         * Tax behavior of the checkout. `inclusive` means the price includes tax, `exclusive` means
         * tax is added on top. If `null`, tax is not yet calculated.
         */
        public readonly ?TaxBehavior $taxBehavior,
        /**
         * Amount in cents, after discounts and taxes.
         */
        public readonly int $totalAmount,
        /**
         * Currency code of the checkout session.
         */
        public readonly string $currency,
        /**
         * Whether to enable the trial period for the checkout session. If `false`, the trial period
         * will be disabled, even if the selected product has a trial configured.
         */
        public readonly ?bool $allowTrial,
        /**
         * Interval unit of the trial period, if any. This value is either set from the checkout, if
         * `trial_interval` is set, or from the selected product.
         */
        public readonly ?TrialInterval $activeTrialInterval,
        /**
         * Number of interval units of the trial period, if any. This value is either set from the
         * checkout, if `trial_interval_count` is set, or from the selected product.
         */
        public readonly ?int $activeTrialIntervalCount,
        /**
         * End date and time of the trial period, if any.
         */
        public readonly ?CarbonImmutable $trialEnd,
        /**
         * ID of the organization owning the checkout session.
         */
        public readonly string $organizationId,
        /**
         * ID of the product to checkout.
         */
        public readonly ?string $productId,
        /**
         * ID of the product price to checkout.
         */
        public readonly ?string $productPriceId,
        /**
         * ID of the discount applied to the checkout.
         */
        public readonly ?string $discountId,
        /**
         * Whether to allow the customer to apply discount codes. If you apply a discount through
         * `discount_id`, it'll still be applied, but the customer won't be able to change it.
         */
        public readonly bool $allowDiscountCodes,
        /**
         * Whether to require the customer to fill their full billing address, instead of just the
         * country. Customers in the US will always be required to fill their full address, regardless
         * of this setting. If you preset the billing address, this setting will be automatically set
         * to `true`.
         */
        public readonly bool $requireBillingAddress,
        /**
         * Whether the discount is applicable to the checkout. Typically, free and custom prices are
         * not discountable.
         */
        public readonly bool $isDiscountApplicable,
        /**
         * Whether the product price is free, regardless of discounts.
         */
        public readonly bool $isFreeProductPrice,
        /**
         * Whether the checkout requires payment, e.g. in case of free products or discounts that cover
         * the total amount.
         */
        public readonly bool $isPaymentRequired,
        /**
         * Whether the checkout requires setting up a payment method, regardless of the amount, e.g.
         * subscriptions that have first free cycles.
         */
        public readonly bool $isPaymentSetupRequired,
        /**
         * Whether the checkout requires a payment form, whether because of a payment or payment method
         * setup.
         */
        public readonly bool $isPaymentFormRequired,
        public readonly ?string $customerId,
        /**
         * Whether the customer is a business or an individual. If `true`, the customer will be
         * required to fill their full billing address and billing name.
         */
        public readonly bool $isBusinessCustomer,
        /**
         * Name of the customer.
         */
        public readonly ?string $customerName,
        /**
         * Email address of the customer.
         */
        public readonly ?string $customerEmail,
        public readonly ?string $customerIpAddress,
        public readonly ?string $customerBillingName,
        public readonly ?Address $customerBillingAddress,
        public readonly ?string $customerTaxId,
        /**
         * Payment method type selected by the customer in the checkout form, e.g. `card`, `apple_pay`
         * or `upi`.
         */
        public readonly ?string $paymentMethodType,
        /**
         * @var array<string, mixed>
         */
        public readonly array $paymentProcessorMetadata,
        /**
         * Determine which billing address fields should be disabled, optional or required in the
         * checkout form.
         */
        public readonly CheckoutBillingAddressFields $billingAddressFields,
        /**
         * The interval unit for the trial period.
         */
        public readonly ?TrialInterval $trialInterval,
        /**
         * The number of interval units for the trial period.
         */
        public readonly ?int $trialIntervalCount,
        /**
         * @var array<string, mixed>
         */
        public readonly array $metadata,
        /**
         * ID of the customer in your system. If a matching customer exists on Polar, the resulting
         * order will be linked to this customer. Otherwise, a new customer will be created with this
         * external ID set.
         */
        public readonly ?string $externalCustomerId,
        /**
         * List of products available to select.
         *
         * @var list<CheckoutProduct>
         */
        public readonly array $products,
        /**
         * Product selected to checkout.
         */
        public readonly ?CheckoutProduct $product,
        /**
         * Price of the selected product.
         *
         * @var LegacyRecurringProductPrice|ProductPrice|null
         */
        public readonly LegacyRecurringProductPrice|ProductPrice|null $productPrice,
        /**
         * Mapping of product IDs to their list of prices.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $prices,
        /**
         * @var CheckoutDiscountFixedOnceForeverDuration|CheckoutDiscountFixedRepeatDuration|CheckoutDiscountPercentageOnceForeverDuration|CheckoutDiscountPercentageRepeatDuration|null
         */
        public readonly CheckoutDiscountFixedOnceForeverDuration|CheckoutDiscountFixedRepeatDuration|CheckoutDiscountPercentageOnceForeverDuration|CheckoutDiscountPercentageRepeatDuration|null $discount,
        public readonly ?string $subscriptionId,
        /**
         * @var list<AttachedCustomField>|null
         */
        public readonly ?array $attachedCustomFields,
        /**
         * @var array<string, mixed>
         */
        public readonly array $customerMetadata,
        /**
         * Key-value object storing custom field values.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $customFieldData = null,
        /**
         * Predefined number of seats (works with seat-based pricing only)
         */
        public readonly ?int $seats = null,
        /**
         * Minimum number of seats (works with seat-based pricing only)
         */
        public readonly ?int $minSeats = null,
        /**
         * Maximum number of seats (works with seat-based pricing only)
         */
        public readonly ?int $maxSeats = null,
        public readonly ?string $locale = null,
    ) {}
}
