<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\DiscountDuration;
use Danestves\LaravelPolar\Enums\DiscountType;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema for a fixed amount discount that is applied once or forever.
 */
#[MapName(SnakeCaseMapper::class)]
class CheckoutDiscountFixedOnceForeverDuration extends PolarData
{
    public function __construct(
        public readonly DiscountDuration $duration,
        public readonly DiscountType $type,
        public readonly int $amount,
        public readonly string $currency,
        /**
         * Map of currency to fixed amount to discount from the total.
         *
         * @var array<string, mixed>
         */
        public readonly array $amounts,
        /**
         * The ID of the object.
         */
        public readonly string $id,
        public readonly string $name,
        public readonly ?string $code,
    ) {}
}
