<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\DiscountDuration;
use Danestves\LaravelPolar\Enums\DiscountType;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Attributes\PropertyForMorph;
use Spatie\LaravelData\Contracts\PropertyMorphableData;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
abstract class CheckoutDiscount extends PolarData implements PropertyMorphableData
{
    #[PropertyForMorph]
    public DiscountDuration $duration;

    #[PropertyForMorph]
    public DiscountType $type;

    /**
     * The ID of the object.
     */
    public string $id;

    public string $name;

    public ?string $code;

    public static function morph(array $properties): ?string
    {
        $repeating = match ($properties['duration']) {
            DiscountDuration::Repeating => true,
            DiscountDuration::Once, DiscountDuration::Forever => false,
            default => null,
        };

        if ($repeating === null) {
            return null;
        }

        return match ($properties['type']) {
            DiscountType::Fixed => $repeating
                ? CheckoutDiscountFixedRepeatDuration::class
                : CheckoutDiscountFixedOnceForeverDuration::class,
            DiscountType::Percentage => $repeating
                ? CheckoutDiscountPercentageRepeatDuration::class
                : CheckoutDiscountPercentageOnceForeverDuration::class,
            default => null,
        };
    }
}
