<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\PaymentProcessor;
use Danestves\LaravelPolar\Enums\TrialInterval;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Checkout link data.
 */
#[MapName(SnakeCaseMapper::class)]
class CheckoutLink extends PolarData
{
    public function __construct(
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The interval unit for the trial period.
         */
        public readonly ?TrialInterval $trialInterval,
        /**
         * The number of interval units for the trial period.
         */
        public readonly ?int $trialIntervalCount,
        /**
         * @var array<string, mixed>
         */
        public readonly array $metadata,
        /**
         * Payment processor used.
         */
        public readonly PaymentProcessor $paymentProcessor,
        /**
         * Client secret used to access the checkout link.
         */
        public readonly string $clientSecret,
        /**
         * URL where the customer will be redirected after a successful payment.
         */
        public readonly ?string $successUrl,
        /**
         * When set, a back button will be shown in the checkout to return to this URL.
         */
        public readonly ?string $returnUrl,
        /**
         * Optional label to distinguish links internally
         */
        public readonly ?string $label,
        /**
         * Whether to allow the customer to apply discount codes. If you apply a discount through
         * `discount_id`, it'll still be applied, but the customer won't be able to change it.
         */
        public readonly bool $allowDiscountCodes,
        /**
         * Whether to require the customer to fill their full billing address, instead of just the
         * country. Customers in the US will always be required to fill their full address, regardless
         * of this setting.
         */
        public readonly bool $requireBillingAddress,
        /**
         * ID of the discount to apply to the checkout. If the discount is not applicable anymore when
         * opening the checkout link, it'll be ignored.
         */
        public readonly ?string $discountId,
        /**
         * Preconfigured number of seats for seat-based pricing. When set, checkout sessions created
         * from this link are locked to this number of seats and the customer won't be able to change
         * it. All products on the link must use seat-based pricing and allow this number of seats. If
         * the products no longer accommodate this value when the link is opened, it'll be ignored.
         */
        public readonly ?int $seats,
        /**
         * The organization ID.
         */
        public readonly string $organizationId,
        /**
         * @var list<CheckoutLinkProduct>
         */
        public readonly array $products,
        /**
         * @var DiscountFixedOnceForeverDurationBase|DiscountFixedRepeatDurationBase|DiscountPercentageOnceForeverDurationBase|DiscountPercentageRepeatDurationBase|null
         */
        public readonly DiscountFixedOnceForeverDurationBase|DiscountFixedRepeatDurationBase|DiscountPercentageOnceForeverDurationBase|DiscountPercentageRepeatDurationBase|null $discount,
        public readonly string $url,
    ) {}
}
