<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\TrialInterval;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema to update an existing checkout link.
 */
#[MapName(SnakeCaseMapper::class)]
class CheckoutLinkUpdate extends Data
{
    public function __construct(
        /**
         * The interval unit for the trial period.
         */
        public readonly ?TrialInterval $trialInterval = null,
        /**
         * The number of interval units for the trial period.
         */
        public readonly ?int $trialIntervalCount = null,
        /**
         * Key-value object allowing you to store additional information.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $metadata = null,
        /**
         * List of products that will be available to select at checkout.
         *
         * @var list<string>|null
         */
        public readonly ?array $products = null,
        public readonly ?string $label = null,
        /**
         * Whether to allow the customer to apply discount codes. If you apply a discount through
         * `discount_id`, it'll still be applied, but the customer won't be able to change it.
         */
        public readonly ?bool $allowDiscountCodes = null,
        /**
         * Whether to require the customer to fill their full billing address, instead of just the
         * country. Customers in the US will always be required to fill their full address, regardless
         * of this setting.
         */
        public readonly ?bool $requireBillingAddress = null,
        /**
         * ID of the discount to apply to the checkout. If the discount is not applicable anymore when
         * opening the checkout link, it'll be ignored.
         */
        public readonly ?string $discountId = null,
        /**
         * Preconfigured number of seats for seat-based pricing. When set, checkout sessions created
         * from this link are locked to this number of seats and the customer won't be able to change
         * it. All products on the link must use seat-based pricing and allow this number of seats. If
         * the products no longer accommodate this value when the link is opened, it'll be ignored.
         */
        public readonly ?int $seats = null,
        /**
         * URL where the customer will be redirected after a successful payment.You can add the
         * `checkout_id={CHECKOUT_ID}` query parameter to retrieve the checkout session id.
         */
        public readonly ?string $successUrl = null,
        /**
         * When set, a back button will be shown in the checkout to return to this URL.
         */
        public readonly ?string $returnUrl = null,
    ) {}
}
