<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\PresentmentCurrency;
use Danestves\LaravelPolar\Enums\TrialInterval;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Create a new checkout session from a list of products.
 * Customers will be able to switch between those products.
 *
 * Metadata set on the checkout will be copied
 * to the resulting order and/or subscription.
 */
#[MapName(SnakeCaseMapper::class)]
class CheckoutProductsCreate extends Data
{
    public function __construct(
        /**
         * List of product IDs available to select at that checkout. The first one will be selected by
         * default.
         *
         * @var list<string>
         */
        public readonly array $products,
        /**
         * The interval unit for the trial period.
         */
        public readonly ?TrialInterval $trialInterval = null,
        /**
         * The number of interval units for the trial period.
         */
        public readonly ?int $trialIntervalCount = null,
        /**
         * Key-value object allowing you to store additional information.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $metadata = null,
        /**
         * Key-value object storing custom field values.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $customFieldData = null,
        /**
         * ID of the discount to apply to the checkout.
         */
        public readonly ?string $discountId = null,
        /**
         * Whether to allow the customer to apply discount codes. If you apply a discount through
         * `discount_id`, it'll still be applied, but the customer won't be able to change it.
         */
        public readonly ?bool $allowDiscountCodes = null,
        /**
         * Whether to require the customer to fill their full billing address, instead of just the
         * country. Customers in the US will always be required to fill their full address, regardless
         * of this setting. If you preset the billing address, this setting will be automatically set
         * to `true`.
         */
        public readonly ?bool $requireBillingAddress = null,
        public readonly ?int $amount = null,
        /**
         * Predefined number of seats (works with seat-based pricing only)
         */
        public readonly ?int $seats = null,
        /**
         * Minimum number of seats (works with seat-based pricing only)
         */
        public readonly ?int $minSeats = null,
        /**
         * Maximum number of seats (works with seat-based pricing only)
         */
        public readonly ?int $maxSeats = null,
        /**
         * Whether to enable the trial period for the checkout session. If `false`, the trial period
         * will be disabled, even if the selected product has a trial configured.
         */
        public readonly ?bool $allowTrial = null,
        /**
         * ID of an existing customer in the organization. The customer data will be pre-filled in the
         * checkout form. The resulting order will be linked to this customer.
         */
        public readonly ?string $customerId = null,
        /**
         * Whether the customer is a business or an individual. If `true`, the customer will be
         * required to fill their full billing address and billing name.
         */
        public readonly ?bool $isBusinessCustomer = null,
        /**
         * ID of the customer in your system. If a matching customer exists on Polar, the resulting
         * order will be linked to this customer. Otherwise, a new customer will be created with this
         * external ID set.
         */
        public readonly ?string $externalCustomerId = null,
        public readonly ?string $customerName = null,
        public readonly ?string $customerEmail = null,
        public readonly ?string $customerIpAddress = null,
        public readonly ?string $customerBillingName = null,
        public readonly ?AddressInput $customerBillingAddress = null,
        public readonly ?string $customerTaxId = null,
        /**
         * Key-value object allowing you to store additional information that'll be copied to the
         * created customer.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $customerMetadata = null,
        /**
         * ID of a subscription to upgrade. It must be on a free pricing. If checkout is successful,
         * metadata set on this checkout will be copied to the subscription, and existing keys will be
         * overwritten.
         */
        public readonly ?string $subscriptionId = null,
        /**
         * URL where the customer will be redirected after a successful payment.You can add the
         * `checkout_id={CHECKOUT_ID}` query parameter to retrieve the checkout session id.
         */
        public readonly ?string $successUrl = null,
        /**
         * When set, a back button will be shown in the checkout to return to this URL.
         */
        public readonly ?string $returnUrl = null,
        /**
         * If you plan to embed the checkout session, set this to the Origin of the embedding page.
         * It'll allow the Polar iframe to communicate with the parent page.
         */
        public readonly ?string $embedOrigin = null,
        public readonly ?string $locale = null,
        public readonly ?PresentmentCurrency $currency = null,
        /**
         * Optional mapping of product IDs to a list of ad-hoc prices to create for that product. If
         * not set, catalog prices of the product will be used.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $prices = null,
    ) {}
}
