<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\BillingAddressFieldMode;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class CheckoutBillingAddressFields extends Data
{
    public function __construct(
        public readonly BillingAddressFieldMode $country,
        public readonly BillingAddressFieldMode $state,
        public readonly BillingAddressFieldMode $city,
        public readonly BillingAddressFieldMode $postalCode,
        public readonly BillingAddressFieldMode $line1,
        public readonly BillingAddressFieldMode $line2,
    ) {}
}
