<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class CostMetadataInput extends PolarData
{
    public function __construct(
        /**
         * The amount in cents.
         *
         * @var float|string
         */
        public readonly float|string $amount,
        /**
         * The currency. Currently, only `usd` is supported.
         */
        public readonly string $currency,
    ) {}
}
