<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class CustomFieldTextProperties extends Data
{
    public function __construct(
        public readonly ?string $formLabel = null,
        public readonly ?string $formHelpText = null,
        public readonly ?string $formPlaceholder = null,
        public readonly ?bool $textarea = null,
        public readonly ?int $minLength = null,
        public readonly ?int $maxLength = null,
    ) {}
}
