<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\SeatStatus;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class CustomerSeat extends Data
{
    public function __construct(
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The seat ID
         */
        public readonly string $id,
        /**
         * The subscription ID (for recurring seats)
         */
        public readonly ?string $subscriptionId,
        /**
         * The order ID (for one-time purchase seats)
         */
        public readonly ?string $orderId,
        /**
         * Status of the seat
         */
        public readonly SeatStatus $status,
        /**
         * The customer ID. When member_model_enabled is true, this is the billing customer
         * (purchaser). When false, this is the seat member customer.
         */
        public readonly ?string $customerId,
        /**
         * The member ID of the seat occupant
         */
        public readonly ?string $memberId,
        /**
         * The member associated with this seat
         */
        public readonly ?Member $member,
        /**
         * Email of the seat member (set when member_model_enabled is true)
         */
        public readonly ?string $email,
        /**
         * The assigned customer email
         */
        public readonly ?string $customerEmail,
        /**
         * When the invitation token expires
         */
        public readonly ?CarbonImmutable $invitationTokenExpiresAt,
        /**
         * When the seat was claimed
         */
        public readonly ?CarbonImmutable $claimedAt,
        /**
         * When the seat was revoked
         */
        public readonly ?CarbonImmutable $revokedAt,
        /**
         * Additional metadata for the seat
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $seatMetadata,
    ) {}
}
