<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema to update a custom field of type text.
 */
#[MapName(SnakeCaseMapper::class)]
class CustomFieldUpdateText extends PolarData implements CustomFieldUpdate
{
    public function __construct(
        /**
         * Key-value object allowing you to store additional information.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $metadata = null,
        public readonly ?string $name = null,
        public readonly ?string $slug = null,
        public readonly string $type = 'text',
        public readonly ?CustomFieldTextProperties $properties = null,
    ) {}
}
