<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema for creating a customer session using a customer ID.
 */
#[MapName(SnakeCaseMapper::class)]
class CustomerSessionCustomerIDCreate extends PolarData
{
    public function __construct(
        /**
         * ID of the customer to create a session for.
         */
        public readonly string $customerId,
        /**
         * ID of the member to create a session for. When not provided and the organization has
         * `member_model_enabled`, the owner member of the customer will be used for individual
         * customers.
         */
        public readonly ?string $memberId = null,
        /**
         * External ID of the member to create a session for. Alternative to `member_id`.
         */
        public readonly ?string $externalMemberId = null,
        /**
         * When set, a back button will be shown in the customer portal to return to this URL.
         */
        public readonly ?string $returnUrl = null,
    ) {}
}
