<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A team customer along with additional state information:
 *
 * * Active subscriptions
 * * Granted benefits
 * * Active meters
 */
#[MapName(SnakeCaseMapper::class)]
class CustomerStateTeam extends CustomerState
{
    /**
     * The ID of the customer in your system. This must be unique within the organization. Once
     * set, it can't be updated.
     */
    public ?string $externalId = null;

    /**
     * The email address of the customer. This must be unique within the organization.
     */
    public ?string $email = null;

    public ?string $locale = null;

    /**
     * The ID of the customer's default payment method, if any. Use the payment methods endpoint to
     * retrieve its details.
     */
    public ?string $defaultPaymentMethodId = null;
}
