<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\BenefitType;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * An active benefit grant for a customer.
 */
#[MapName(SnakeCaseMapper::class)]
class CustomerStateBenefitGrant extends PolarData
{
    public function __construct(
        /**
         * The ID of the grant.
         */
        public readonly string $id,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The timestamp when the benefit was granted.
         */
        public readonly CarbonImmutable $grantedAt,
        /**
         * The ID of the benefit concerned by this grant.
         */
        public readonly string $benefitId,
        /**
         * The type of the benefit concerned by this grant.
         */
        public readonly BenefitType $benefitType,
        /**
         * The metadata of the benefit concerned by this grant.
         *
         * @var array<string, mixed>
         */
        public readonly array $benefitMetadata,
        /**
         * @var BenefitGrantDiscordProperties|BenefitGrantGitHubRepositoryProperties|BenefitGrantDownloadablesProperties|BenefitGrantLicenseKeysProperties|BenefitGrantCustomProperties|BenefitGrantFeatureFlagProperties|BenefitGrantSlackSharedChannelProperties
         */
        public readonly BenefitGrantDiscordProperties|BenefitGrantGitHubRepositoryProperties|BenefitGrantDownloadablesProperties|BenefitGrantLicenseKeysProperties|BenefitGrantCustomProperties|BenefitGrantFeatureFlagProperties|BenefitGrantSlackSharedChannelProperties $properties,
    ) {}
}
