<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\PaymentProcessor;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Attributes\PropertyForMorph;
use Spatie\LaravelData\Contracts\PropertyMorphableData;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
abstract class CustomerPaymentMethod extends Data implements PropertyMorphableData
{
    /**
     * The ID of the object.
     */
    public string $id;

    /**
     * Creation timestamp of the object.
     */
    public CarbonImmutable $createdAt;

    /**
     * Last modification timestamp of the object.
     */
    public ?CarbonImmutable $modifiedAt;

    public PaymentProcessor $processor;

    public string $customerId;

    #[PropertyForMorph]
    public string $type;

    public static function morph(array $properties): ?string
    {
        return $properties['type'] === 'card'
            ? PaymentMethodCard::class
            : PaymentMethodGeneric::class;
    }
}
