<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema for a custom field of type checkbox.
 */
#[MapName(SnakeCaseMapper::class)]
class CustomFieldCheckbox extends CustomField
{
    public CustomFieldCheckboxProperties $properties;
}
