<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Current consumption and spending for a subscription meter.
 */
#[MapName(SnakeCaseMapper::class)]
class CustomerStateSubscriptionMeter extends Data
{
    public function __construct(
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * The number of consumed units so far in this billing period.
         */
        public readonly float $consumedUnits,
        /**
         * The number of credited units so far in this billing period.
         */
        public readonly int $creditedUnits,
        /**
         * The amount due in cents so far in this billing period.
         */
        public readonly int $amount,
        /**
         * The ID of the meter.
         */
        public readonly string $meterId,
    ) {}
}
