<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Attributes\PropertyForMorph;
use Spatie\LaravelData\Contracts\PropertyMorphableData;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
abstract class CustomField extends PolarData implements PropertyMorphableData
{
    /**
     * Creation timestamp of the object.
     */
    public CarbonImmutable $createdAt;

    /**
     * Last modification timestamp of the object.
     */
    public ?CarbonImmutable $modifiedAt;

    /**
     * The ID of the object.
     */
    public string $id;

    /**
     * @var array<string, mixed>
     */
    public array $metadata;

    #[PropertyForMorph]
    public string $type;

    /**
     * Identifier of the custom field. It'll be used as key when storing the value.
     */
    public string $slug;

    /**
     * Name of the custom field.
     */
    public string $name;

    /**
     * The ID of the organization owning the custom field.
     */
    public string $organizationId;

    public static function morph(array $properties): ?string
    {
        return match ($properties['type']) {
            'checkbox' => CustomFieldCheckbox::class,
            'date' => CustomFieldDate::class,
            'number' => CustomFieldNumber::class,
            'select' => CustomFieldSelect::class,
            'text' => CustomFieldText::class,
            default => null,
        };
    }
}
