<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class CustomerPortalSubscriptionSettings extends Data
{
    public function __construct(
        public readonly bool $updateSeats,
        public readonly bool $updatePlan,
        public readonly ?bool $pause = null,
    ) {}
}
