<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema to create a custom field of type date.
 */
#[MapName(SnakeCaseMapper::class)]
class CustomFieldCreateDate extends PolarData implements CustomFieldCreate
{
    public function __construct(
        /**
         * Identifier of the custom field. It'll be used as key when storing the value. Must be unique
         * across the organization.It can only contain ASCII letters, numbers and hyphens.
         */
        public readonly string $slug,
        /**
         * Name of the custom field.
         */
        public readonly string $name,
        public readonly CustomFieldDateProperties $properties,
        /**
         * Key-value object allowing you to store additional information.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $metadata = null,
        public readonly string $type = 'date',
        /**
         * The ID of the organization owning the custom field. **Required unless you use an
         * organization token.**
         */
        public readonly ?string $organizationId = null,
    ) {}
}
