<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A customer session that can be used to authenticate as a customer.
 */
#[MapName(SnakeCaseMapper::class)]
class CustomerSession extends PolarData
{
    public function __construct(
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the object.
         */
        public readonly string $id,
        public readonly string $token,
        public readonly CarbonImmutable $expiresAt,
        public readonly ?string $returnUrl,
        public readonly string $customerPortalUrl,
        public readonly string $customerId,
        public readonly Customer $customer,
    ) {}
}
