<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Attributes\PropertyForMorph;
use Spatie\LaravelData\Contracts\PropertyMorphableData;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
abstract class Customer extends Data implements PropertyMorphableData
{
    /**
     * The ID of the customer.
     */
    public string $id;

    /**
     * Creation timestamp of the object.
     */
    public CarbonImmutable $createdAt;

    /**
     * Last modification timestamp of the object.
     */
    public ?CarbonImmutable $modifiedAt;

    /**
     * @var array<string, mixed>
     */
    public array $metadata;

    /**
     * Whether the customer email address is verified. The address is automatically verified when
     * the customer accesses the customer portal using their email address.
     */
    public bool $emailVerified;

    #[PropertyForMorph]
    public string $type;

    /**
     * The name of the customer.
     */
    public ?string $name;

    /**
     * The name that should appear on the customer's invoices. Falls back to the customer name when
     * not explicitly set.
     */
    public ?string $billingName;

    public ?Address $billingAddress;

    /**
     * @var list<mixed>|null
     */
    public ?array $taxId;

    /**
     * The ID of the organization owning the customer.
     */
    public string $organizationId;

    /**
     * Timestamp for when the customer was soft deleted.
     */
    public ?CarbonImmutable $deletedAt;

    /**
     * Timestamp of the first event ingested for this customer. Can predate `created_at`, and is
     * null if no event was ever ingested.
     */
    public ?CarbonImmutable $firstUserEventAt;

    public ?string $avatarUrl;

    public static function morph(array $properties): ?string
    {
        return match ($properties['type']) {
            'individual' => CustomerIndividual::class,
            'team' => CustomerTeam::class,
            default => null,
        };
    }
}
