<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class CustomFieldSelectProperties extends PolarData
{
    public function __construct(
        /**
         * @var list<CustomFieldSelectOption>
         */
        public readonly array $options,
        public readonly ?string $formLabel = null,
        public readonly ?string $formHelpText = null,
        public readonly ?string $formPlaceholder = null,
    ) {}
}
