<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * An active customer meter, with current consumed and credited units.
 */
#[MapName(SnakeCaseMapper::class)]
class CustomerMeter extends Data
{
    public function __construct(
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the customer.
         */
        public readonly string $customerId,
        /**
         * The ID of the meter.
         */
        public readonly string $meterId,
        /**
         * The number of consumed units.
         */
        public readonly float $consumedUnits,
        /**
         * The number of credited units.
         */
        public readonly int $creditedUnits,
        /**
         * The balance of the meter, i.e. the difference between credited and consumed units.
         */
        public readonly float $balance,
        /**
         * The customer associated with this meter.
         */
        public readonly Customer $customer,
        /**
         * The meter associated with this customer.
         */
        public readonly Meter $meter,
    ) {}
}
