<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\RecurringInterval;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * An active customer subscription.
 */
#[MapName(SnakeCaseMapper::class)]
class CustomerStateSubscription extends PolarData
{
    public function __construct(
        /**
         * The ID of the subscription.
         */
        public readonly string $id,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * @var array<string, mixed>
         */
        public readonly array $metadata,
        public readonly string $status,
        /**
         * The amount of the subscription.
         */
        public readonly int $amount,
        /**
         * The currency of the subscription.
         */
        public readonly string $currency,
        /**
         * The interval at which the subscription recurs.
         */
        public readonly RecurringInterval $recurringInterval,
        /**
         * The start timestamp of the current billing period.
         */
        public readonly CarbonImmutable $currentPeriodStart,
        /**
         * The end timestamp of the current billing period.
         */
        public readonly CarbonImmutable $currentPeriodEnd,
        /**
         * The start timestamp of the trial period, if any.
         */
        public readonly ?CarbonImmutable $trialStart,
        /**
         * The end timestamp of the trial period, if any.
         */
        public readonly ?CarbonImmutable $trialEnd,
        /**
         * Whether the subscription will be canceled at the end of the current period.
         */
        public readonly bool $cancelAtPeriodEnd,
        /**
         * The timestamp when the subscription was canceled. The subscription might still be active if
         * `cancel_at_period_end` is `true`.
         */
        public readonly ?CarbonImmutable $canceledAt,
        /**
         * The timestamp when the subscription started.
         */
        public readonly ?CarbonImmutable $startedAt,
        /**
         * The timestamp when the subscription will end.
         */
        public readonly ?CarbonImmutable $endsAt,
        /**
         * The ID of the subscribed product.
         */
        public readonly string $productId,
        /**
         * The ID of the applied discount, if any.
         */
        public readonly ?string $discountId,
        /**
         * List of meters associated with the subscription.
         *
         * @var list<CustomerStateSubscriptionMeter>
         */
        public readonly array $meters,
        /**
         * Key-value object storing custom field values.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $customFieldData = null,
    ) {}
}
