<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Order's invoice data.
 */
#[MapName(SnakeCaseMapper::class)]
class CustomerOrderInvoice extends Data
{
    public function __construct(
        /**
         * The URL to the invoice.
         */
        public readonly string $url,
    ) {}
}
