<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

/**
 * Union of: DiscountFixedCreate, DiscountPercentageCreate
 */
interface DiscountCreate {}
