<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema for a percentage discount that is applied once or forever.
 */
#[MapName(SnakeCaseMapper::class)]
class DiscountPercentageOnceForeverDuration extends Discount
{
    /**
     * Discount percentage in basis points. A basis point is 1/100th of a percent. For example,
     * 1000 basis points equals a 10% discount.
     */
    public int $basisPoints;
}
