<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema for a fixed amount discount that is applied once or forever.
 */
#[MapName(SnakeCaseMapper::class)]
class DiscountFixedOnceForeverDuration extends Discount
{
    public int $amount;

    public string $currency;

    /**
     * Map of currency to fixed amount to discount from the total.
     *
     * @var array<string, mixed>
     */
    public array $amounts;
}
