<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\DiscountDuration;
use Danestves\LaravelPolar\Enums\DiscountType;
use Danestves\LaravelPolar\Enums\PresentmentCurrency;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema to update a discount.
 */
#[MapName(SnakeCaseMapper::class)]
class DiscountUpdate extends PolarData
{
    public function __construct(
        /**
         * Key-value object allowing you to store additional information.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $metadata = null,
        public readonly ?string $name = null,
        /**
         * Code customers can use to apply the discount during checkout. Must be between 3 and 256
         * characters long and contain only alphanumeric characters.If not provided, the discount can
         * only be applied via the API.
         */
        public readonly ?string $code = null,
        /**
         * Optional timestamp after which the discount is redeemable.
         */
        public readonly ?CarbonImmutable $startsAt = null,
        /**
         * Optional timestamp after which the discount is no longer redeemable.
         */
        public readonly ?CarbonImmutable $endsAt = null,
        /**
         * Optional maximum number of times the discount can be redeemed.
         */
        public readonly ?int $maxRedemptions = null,
        /**
         * Optional maximum number of times the discount can be redeemed by a single customer.
         */
        public readonly ?int $maxRedemptionsPerCustomer = null,
        public readonly ?DiscountDuration $duration = null,
        public readonly ?int $durationInMonths = null,
        public readonly ?DiscountType $type = null,
        public readonly ?int $amount = null,
        public readonly ?PresentmentCurrency $currency = null,
        /**
         * @var array<string, mixed>|null
         */
        public readonly ?array $amounts = null,
        public readonly ?int $basisPoints = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $products = null,
    ) {}
}
