<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\DiscountDuration;
use Danestves\LaravelPolar\Enums\DiscountType;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class DiscountFixedRepeatDurationBase extends PolarData
{
    public function __construct(
        public readonly DiscountDuration $duration,
        public readonly int $durationInMonths,
        public readonly DiscountType $type,
        public readonly int $amount,
        public readonly string $currency,
        /**
         * Map of currency to fixed amount to discount from the total.
         *
         * @var array<string, mixed>
         */
        public readonly array $amounts,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * @var array<string, mixed>
         */
        public readonly array $metadata,
        /**
         * Name of the discount. Will be displayed to the customer when the discount is applied.
         */
        public readonly string $name,
        /**
         * Code customers can use to apply the discount during checkout.
         */
        public readonly ?string $code,
        /**
         * Timestamp after which the discount is redeemable.
         */
        public readonly ?CarbonImmutable $startsAt,
        /**
         * Timestamp after which the discount is no longer redeemable.
         */
        public readonly ?CarbonImmutable $endsAt,
        /**
         * Maximum number of times the discount can be redeemed.
         */
        public readonly ?int $maxRedemptions,
        /**
         * Maximum number of times the discount can be redeemed by a single customer.
         */
        public readonly ?int $maxRedemptionsPerCustomer,
        /**
         * Number of times the discount has been redeemed.
         */
        public readonly int $redemptionsCount,
        /**
         * The organization ID.
         */
        public readonly string $organizationId,
    ) {}
}
