<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\DiscountDuration;
use Danestves\LaravelPolar\Enums\DiscountType;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Attributes\PropertyForMorph;
use Spatie\LaravelData\Contracts\PropertyMorphableData;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
abstract class DiscountBase extends PolarData implements PropertyMorphableData
{
    #[PropertyForMorph]
    public DiscountDuration $duration;

    #[PropertyForMorph]
    public DiscountType $type;

    /**
     * Creation timestamp of the object.
     */
    public CarbonImmutable $createdAt;

    /**
     * Last modification timestamp of the object.
     */
    public ?CarbonImmutable $modifiedAt;

    /**
     * The ID of the object.
     */
    public string $id;

    /**
     * @var array<string, mixed>
     */
    public array $metadata;

    /**
     * Name of the discount. Will be displayed to the customer when the discount is applied.
     */
    public string $name;

    /**
     * Code customers can use to apply the discount during checkout.
     */
    public ?string $code;

    /**
     * Timestamp after which the discount is redeemable.
     */
    public ?CarbonImmutable $startsAt;

    /**
     * Timestamp after which the discount is no longer redeemable.
     */
    public ?CarbonImmutable $endsAt;

    /**
     * Maximum number of times the discount can be redeemed.
     */
    public ?int $maxRedemptions;

    /**
     * Maximum number of times the discount can be redeemed by a single customer.
     */
    public ?int $maxRedemptionsPerCustomer;

    /**
     * Number of times the discount has been redeemed.
     */
    public int $redemptionsCount;

    /**
     * The organization ID.
     */
    public string $organizationId;

    public static function morph(array $properties): ?string
    {
        $repeating = match ($properties['duration']) {
            DiscountDuration::Repeating => true,
            DiscountDuration::Once, DiscountDuration::Forever => false,
            default => null,
        };

        if ($repeating === null) {
            return null;
        }

        return match ($properties['type']) {
            DiscountType::Fixed => $repeating
                ? DiscountFixedRepeatDurationBase::class
                : DiscountFixedOnceForeverDurationBase::class,
            DiscountType::Percentage => $repeating
                ? DiscountPercentageRepeatDurationBase::class
                : DiscountPercentageOnceForeverDurationBase::class,
            default => null,
        };
    }
}
