<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\DiscountDuration;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema to create a percentage discount.
 */
#[MapName(SnakeCaseMapper::class)]
class DiscountPercentageCreate extends PolarData implements DiscountCreate
{
    public function __construct(
        /**
         * Name of the discount. Will be displayed to the customer when the discount is applied.
         */
        public readonly string $name,
        /**
         * For subscriptions, determines if the discount should be applied once on the first invoice,
         * forever, or for a certain number of months determined by `duration_in_months`.
         */
        public readonly DiscountDuration $duration,
        /**
         * Discount percentage in basis points.
         *
         * A basis point is 1/100th of a percent.
         * For example, to create a 25.5% discount, set this to 2550.
         */
        public readonly int $basisPoints,
        /**
         * Key-value object allowing you to store additional information.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $metadata = null,
        /**
         * Code customers can use to apply the discount during checkout. Must be between 3 and 256
         * characters long and contain only alphanumeric characters.If not provided, the discount can
         * only be applied via the API.
         */
        public readonly ?string $code = null,
        /**
         * Optional timestamp after which the discount is redeemable.
         */
        public readonly ?CarbonImmutable $startsAt = null,
        /**
         * Optional timestamp after which the discount is no longer redeemable.
         */
        public readonly ?CarbonImmutable $endsAt = null,
        /**
         * Optional maximum number of times the discount can be redeemed.
         */
        public readonly ?int $maxRedemptions = null,
        /**
         * Optional maximum number of times the discount can be redeemed by a single customer.
         */
        public readonly ?int $maxRedemptionsPerCustomer = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $products = null,
        /**
         * The ID of the organization owning the discount. **Required unless you use an organization
         * token.**
         */
        public readonly ?string $organizationId = null,
        public readonly string $type = 'percentage',
        /**
         * Number of months the discount should be applied.
         *
         * Required when `duration` is `repeating`. Must be omitted otherwise.
         *
         * For this to work on yearly pricing, you should multiply this by 12.
         * For example, to apply the discount for 2 years, set this to 24.
         */
        public readonly ?int $durationInMonths = null,
    ) {}
}
