<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * File to be associated with the downloadables benefit.
 */
#[MapName(SnakeCaseMapper::class)]
class DownloadableFileRead extends FileRead
{
    public ?CarbonImmutable $flaggedMaliciousAt;
}
