<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class EventsIngestResponse extends PolarData
{
    public function __construct(
        /**
         * Number of events inserted.
         */
        public readonly int $inserted,
        /**
         * Number of duplicate events skipped.
         */
        public readonly ?int $duplicates = null,
    ) {}
}
