<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class EventCreateCustomer extends Data
{
    public function __construct(
        /**
         * The name of the event.
         */
        public readonly string $name,
        /**
         * ID of the customer in your Polar organization associated with the event.
         */
        public readonly string $customerId,
        /**
         * The timestamp of the event.
         */
        public readonly ?CarbonImmutable $timestamp = null,
        /**
         * The ID of the organization owning the event. **Required unless you use an organization
         * token.**
         */
        public readonly ?string $organizationId = null,
        /**
         * Your unique identifier for this event. Useful for deduplication and parent-child
         * relationships.
         */
        public readonly ?string $externalId = null,
        /**
         * The ID of the parent event. Can be either a Polar event ID (UUID) or an external event ID.
         */
        public readonly ?string $parentId = null,
        /**
         * Key-value object allowing you to store additional information about the event. Some keys
         * like `_llm` are structured data that are handled specially by Polar.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $metadata = null,
        /**
         * ID of the member within the customer's organization who performed the action. Used for
         * member-level attribution in B2B.
         */
        public readonly ?string $memberId = null,
    ) {}
}
