<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class EventsIngest extends PolarData
{
    public function __construct(
        /**
         * List of events to ingest.
         *
         * @var list<EventCreateCustomer|EventCreateExternalCustomer>
         */
        public readonly array $events,
    ) {}
}
