<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Attributes\PropertyForMorph;
use Spatie\LaravelData\Contracts\PropertyMorphableData;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
abstract class FileRead extends PolarData implements PropertyMorphableData
{
    /**
     * The ID of the object.
     */
    public string $id;

    public string $organizationId;

    public string $name;

    public string $path;

    public string $mimeType;

    public int $size;

    public ?string $storageVersion;

    public ?string $checksumEtag;

    public ?string $checksumSha256Base64;

    public ?string $checksumSha256Hex;

    public ?CarbonImmutable $lastModifiedAt;

    public ?string $version;

    #[PropertyForMorph]
    public string $service;

    public bool $isUploaded;

    public CarbonImmutable $createdAt;

    public string $sizeReadable;

    public static function morph(array $properties): ?string
    {
        return match ($properties['service']) {
            'downloadable' => DownloadableFileRead::class,
            'organization_avatar' => OrganizationAvatarFileRead::class,
            'product_media' => ProductMediaFileRead::class,
            'support_case_attachment' => SupportCaseAttachmentFileRead::class,
            default => null,
        };
    }
}
