<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\FilterConjunction;
use Danestves\LaravelPolar\Support\FilterClausesCast;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Attributes\WithCast;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class Filter extends PolarData
{
    public function __construct(
        public readonly FilterConjunction $conjunction,
        /**
         * @var list<FilterClause|Filter>
         */
        #[WithCast(FilterClausesCast::class)]
        public readonly array $clauses,
    ) {}
}
