<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A recurring price for a product, i.e. a subscription.
 *
 * **Deprecated**: The recurring interval should be set on the product itself.
 */
#[MapName(SnakeCaseMapper::class)]
class LegacyRecurringProductPriceFixed extends LegacyRecurringProductPrice
{
    /**
     * The price in cents.
     */
    public int $priceAmount;
}
