<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\ProductPriceSource;
use Danestves\LaravelPolar\Enums\RecurringInterval;
use Danestves\LaravelPolar\Enums\TaxBehaviorOption;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Attributes\PropertyForMorph;
use Spatie\LaravelData\Contracts\PropertyMorphableData;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
abstract class LegacyRecurringProductPrice extends Data implements PropertyMorphableData
{
    /**
     * Creation timestamp of the object.
     */
    public CarbonImmutable $createdAt;

    /**
     * Last modification timestamp of the object.
     */
    public ?CarbonImmutable $modifiedAt;

    /**
     * The ID of the price.
     */
    public string $id;

    /**
     * The source of the price . `catalog` is a predefined price, while `ad_hoc` is a price created
     * dynamically on a Checkout session.
     */
    public ProductPriceSource $source;

    #[PropertyForMorph]
    public string $amountType;

    /**
     * The currency in which the customer will be charged.
     */
    public string $priceCurrency;

    /**
     * The tax behavior of the price. If null, it defaults to the organization's default tax
     * behavior.
     */
    public ?TaxBehaviorOption $taxBehavior;

    /**
     * Whether the price is archived and no longer available.
     */
    public bool $isArchived;

    /**
     * The ID of the product owning the price.
     */
    public string $productId;

    public string $type;

    /**
     * The recurring interval of the price.
     */
    public RecurringInterval $recurringInterval;

    public string $legacy;

    public static function morph(array $properties): ?string
    {
        return match ($properties['amountType']) {
            'custom' => LegacyRecurringProductPriceCustom::class,
            'fixed' => LegacyRecurringProductPriceFixed::class,
            default => null,
        };
    }
}
