<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\CustomerType;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class LicenseKeyCustomer extends Data
{
    public function __construct(
        /**
         * The ID of the customer.
         */
        public readonly string $id,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * @var array<string, mixed>
         */
        public readonly array $metadata,
        /**
         * Whether the customer email address is verified. The address is automatically verified when
         * the customer accesses the customer portal using their email address.
         */
        public readonly bool $emailVerified,
        /**
         * The type of customer: 'individual' for single users, 'team' for customers with multiple
         * members.
         */
        public readonly CustomerType $type,
        /**
         * The name of the customer.
         */
        public readonly ?string $name,
        /**
         * The name that should appear on the customer's invoices. Falls back to the customer name when
         * not explicitly set.
         */
        public readonly ?string $billingName,
        public readonly ?Address $billingAddress,
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $taxId,
        /**
         * The ID of the organization owning the customer.
         */
        public readonly string $organizationId,
        /**
         * Timestamp for when the customer was soft deleted.
         */
        public readonly ?CarbonImmutable $deletedAt,
        /**
         * Timestamp of the first event ingested for this customer. Can predate `created_at`, and is
         * null if no event was ever ingested.
         */
        public readonly ?CarbonImmutable $firstUserEventAt,
        public readonly ?string $avatarUrl,
        /**
         * The ID of the customer in your system. This must be unique within the organization. Once
         * set, it can't be updated.
         */
        public readonly ?string $externalId = null,
        /**
         * The email address of the customer. This must be unique within the organization.
         */
        public readonly ?string $email = null,
        public readonly ?string $locale = null,
        /**
         * The ID of the customer's default payment method, if any. Use the payment methods endpoint to
         * retrieve its details.
         */
        public readonly ?string $defaultPaymentMethodId = null,
    ) {}
}
