<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class LicenseKeyDeactivate extends PolarData
{
    public function __construct(
        public readonly string $key,
        public readonly string $organizationId,
        public readonly string $activationId,
    ) {}
}
