<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\LicenseKeyStatus;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class LicenseKeyUpdate extends Data
{
    public function __construct(
        public readonly ?LicenseKeyStatus $status = null,
        public readonly ?int $usage = null,
        public readonly ?int $limitActivations = null,
        public readonly ?int $limitUsage = null,
        public readonly ?CarbonImmutable $expiresAt = null,
    ) {}
}
