<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class LicenseKeyValidate extends PolarData
{
    public function __construct(
        public readonly string $key,
        public readonly string $organizationId,
        public readonly ?string $activationId = null,
        public readonly ?string $benefitId = null,
        public readonly ?string $customerId = null,
        public readonly ?int $incrementUsage = null,
        /**
         * Key-value object allowing you to set conditions that must match when validating the license
         * key.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $conditions = null,
    ) {}
}
