<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\LicenseKeyStatus;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class LicenseKeyWithActivations extends PolarData
{
    public function __construct(
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        public readonly string $organizationId,
        public readonly string $customerId,
        public readonly LicenseKeyCustomer $customer,
        /**
         * The benefit ID.
         */
        public readonly string $benefitId,
        public readonly string $key,
        public readonly string $displayKey,
        public readonly LicenseKeyStatus $status,
        public readonly ?int $limitActivations,
        public readonly int $usage,
        public readonly ?int $limitUsage,
        public readonly int $validations,
        public readonly ?CarbonImmutable $lastValidatedAt,
        public readonly ?CarbonImmutable $expiresAt,
        /**
         * @var list<LicenseKeyActivationBase>
         */
        public readonly array $activations,
    ) {}
}
