<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class LLMMetadata extends PolarData
{
    public function __construct(
        /**
         * The vendor of the event.
         */
        public readonly string $vendor,
        /**
         * The model used for the event.
         */
        public readonly string $model,
        /**
         * The number of LLM input tokens used for the event.
         */
        public readonly int $inputTokens,
        /**
         * The number of LLM output tokens used for the event.
         */
        public readonly int $outputTokens,
        /**
         * The total number of LLM tokens used for the event.
         */
        public readonly int $totalTokens,
        /**
         * The LLM prompt used for the event.
         */
        public readonly ?string $prompt = null,
        /**
         * The LLM response used for the event.
         */
        public readonly ?string $response = null,
        /**
         * The number of LLM cached tokens that were used for the event.
         */
        public readonly ?int $cachedInputTokens = null,
    ) {}
}
