<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\MemberRole;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A member of a customer.
 */
#[MapName(SnakeCaseMapper::class)]
class Member extends Data
{
    public function __construct(
        /**
         * The ID of the member.
         */
        public readonly string $id,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the customer this member belongs to.
         */
        public readonly string $customerId,
        /**
         * The email address of the member.
         */
        public readonly string $email,
        /**
         * The name of the member.
         */
        public readonly ?string $name,
        /**
         * The ID of the member in your system. This must be unique within the customer.
         */
        public readonly ?string $externalId,
        /**
         * The role of the member within the customer.
         */
        public readonly MemberRole $role,
    ) {}
}
