<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\MeterUnit;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class Meter extends Data
{
    public function __construct(
        /**
         * @var array<string, mixed>
         */
        public readonly array $metadata,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * The name of the meter. Will be shown on customer's invoices and usage.
         */
        public readonly string $name,
        /**
         * The unit of the meter.
         */
        public readonly MeterUnit $unit,
        /**
         * The filter to apply on events that'll be used to calculate the meter.
         */
        public readonly Filter $filter,
        /**
         * The aggregation to apply on the filtered events to calculate the meter.
         *
         * @var CountAggregation|PropertyAggregation|UniqueAggregation
         */
        public readonly CountAggregation|PropertyAggregation|UniqueAggregation $aggregation,
        /**
         * The ID of the organization owning the meter.
         */
        public readonly string $organizationId,
        /**
         * The label for the custom unit.
         */
        public readonly ?string $customLabel = null,
        /**
         * The multiplier to convert from base unit to display scale.
         */
        public readonly ?int $customMultiplier = null,
        /**
         * Whether the meter is archived and the time it was archived.
         */
        public readonly ?CarbonImmutable $archivedAt = null,
    ) {}
}
