<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Metrics response schema.
 */
#[MapName(SnakeCaseMapper::class)]
class MetricsResponse extends Data
{
    public function __construct(
        /**
         * List of data for each timestamp.
         *
         * @var list<MetricPeriod>
         */
        public readonly array $periods,
        /**
         * Totals for the whole selected period.
         */
        public readonly MetricsTotals $totals,
        /**
         * Information about the returned metrics.
         */
        public readonly Metrics $metrics,
    ) {}
}
