<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\MetricType;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Information about a metric.
 */
#[MapName(SnakeCaseMapper::class)]
class Metric extends PolarData
{
    public function __construct(
        /**
         * Unique identifier for the metric.
         */
        public readonly string $slug,
        /**
         * Human-readable name for the metric.
         */
        public readonly string $displayName,
        /**
         * Type of the metric, useful to know the unit or format of the value.
         */
        public readonly MetricType $type,
    ) {}
}
