<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class Metrics extends PolarData
{
    public function __construct(
        public readonly ?Metric $activeSubscriptions = null,
        public readonly ?Metric $committedSubscriptions = null,
        public readonly ?Metric $monthlyRecurringRevenue = null,
        public readonly ?Metric $trialMonthlyRecurringRevenue = null,
        public readonly ?Metric $committedMonthlyRecurringRevenue = null,
        public readonly ?Metric $trialCommittedMonthlyRecurringRevenue = null,
        public readonly ?Metric $averageRevenuePerUser = null,
        public readonly ?Metric $checkouts = null,
        public readonly ?Metric $succeededCheckouts = null,
        public readonly ?Metric $churnedSubscriptions = null,
        public readonly ?Metric $churnRate = null,
        public readonly ?Metric $seatsTotal = null,
        public readonly ?Metric $seatsClaimed = null,
        public readonly ?Metric $seatsPending = null,
        public readonly ?Metric $seatCustomers = null,
        public readonly ?Metric $newSeatCustomers = null,
        public readonly ?Metric $churnedSeatCustomers = null,
        public readonly ?Metric $orders = null,
        public readonly ?Metric $revenue = null,
        public readonly ?Metric $netRevenue = null,
        public readonly ?Metric $cumulativeRevenue = null,
        public readonly ?Metric $netCumulativeRevenue = null,
        public readonly ?Metric $costs = null,
        public readonly ?Metric $cumulativeCosts = null,
        public readonly ?Metric $averageOrderValue = null,
        public readonly ?Metric $netAverageOrderValue = null,
        public readonly ?Metric $costPerUser = null,
        public readonly ?Metric $activeUserByEvent = null,
        public readonly ?Metric $oneTimeProducts = null,
        public readonly ?Metric $oneTimeProductsRevenue = null,
        public readonly ?Metric $oneTimeProductsNetRevenue = null,
        public readonly ?Metric $newSubscriptions = null,
        public readonly ?Metric $newSubscriptionsRevenue = null,
        public readonly ?Metric $newSubscriptionsNetRevenue = null,
        public readonly ?Metric $renewedSubscriptions = null,
        public readonly ?Metric $renewedSubscriptionsRevenue = null,
        public readonly ?Metric $renewedSubscriptionsNetRevenue = null,
        public readonly ?Metric $canceledSubscriptions = null,
        public readonly ?Metric $canceledSubscriptionsCustomerService = null,
        public readonly ?Metric $canceledSubscriptionsLowQuality = null,
        public readonly ?Metric $canceledSubscriptionsMissingFeatures = null,
        public readonly ?Metric $canceledSubscriptionsSwitchedService = null,
        public readonly ?Metric $canceledSubscriptionsTooComplex = null,
        public readonly ?Metric $canceledSubscriptionsTooExpensive = null,
        public readonly ?Metric $canceledSubscriptionsUnused = null,
        public readonly ?Metric $canceledSubscriptionsOther = null,
        public readonly ?Metric $annualRecurringRevenue = null,
        public readonly ?Metric $committedAnnualRecurringRevenue = null,
        public readonly ?Metric $checkoutsConversion = null,
        public readonly ?Metric $ltv = null,
        public readonly ?Metric $grossMargin = null,
        public readonly ?Metric $grossMarginPercentage = null,
        public readonly ?Metric $cashflow = null,
        public readonly ?Metric $averageSeatsPerCustomer = null,
        public readonly ?Metric $seatUtilizationRate = null,
    ) {}
}
