<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class MetricsTotals extends PolarData
{
    public function __construct(
        /**
         * @var int|float|null
         */
        public readonly int|float|null $activeSubscriptions = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $committedSubscriptions = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $monthlyRecurringRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $trialMonthlyRecurringRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $committedMonthlyRecurringRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $trialCommittedMonthlyRecurringRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $averageRevenuePerUser = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $checkouts = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $succeededCheckouts = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $churnedSubscriptions = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $churnRate = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $seatsTotal = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $seatsClaimed = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $seatsPending = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $seatCustomers = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $newSeatCustomers = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $churnedSeatCustomers = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $orders = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $revenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $netRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $cumulativeRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $netCumulativeRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $costs = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $cumulativeCosts = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $averageOrderValue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $netAverageOrderValue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $costPerUser = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $activeUserByEvent = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $oneTimeProducts = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $oneTimeProductsRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $oneTimeProductsNetRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $newSubscriptions = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $newSubscriptionsRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $newSubscriptionsNetRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $renewedSubscriptions = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $renewedSubscriptionsRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $renewedSubscriptionsNetRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $canceledSubscriptions = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $canceledSubscriptionsCustomerService = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $canceledSubscriptionsLowQuality = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $canceledSubscriptionsMissingFeatures = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $canceledSubscriptionsSwitchedService = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $canceledSubscriptionsTooComplex = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $canceledSubscriptionsTooExpensive = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $canceledSubscriptionsUnused = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $canceledSubscriptionsOther = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $annualRecurringRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $committedAnnualRecurringRevenue = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $checkoutsConversion = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $ltv = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $grossMargin = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $grossMarginPercentage = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $cashflow = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $averageSeatsPerCustomer = null,
        /**
         * @var int|float|null
         */
        public readonly int|float|null $seatUtilizationRate = null,
    ) {}
}
