<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\OrderBillingReason;
use Danestves\LaravelPolar\Enums\OrderStatus;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class Order extends Data
{
    public function __construct(
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        public readonly OrderStatus $status,
        /**
         * Whether the order has been paid for.
         */
        public readonly bool $paid,
        /**
         * Amount in cents, before discounts and taxes.
         */
        public readonly int $subtotalAmount,
        /**
         * Discount amount in cents.
         */
        public readonly int $discountAmount,
        /**
         * Amount in cents, after discounts but before taxes.
         */
        public readonly int $netAmount,
        /**
         * Sales tax amount in cents.
         */
        public readonly int $taxAmount,
        /**
         * Amount in cents, after discounts and taxes.
         */
        public readonly int $totalAmount,
        /**
         * Customer's balance amount applied to this invoice. Can increase the total amount paid, if
         * the customer has a negative balance,  or decrease it, if the customer has a positive
         * balance.Amount in cents.
         */
        public readonly int $appliedBalanceAmount,
        /**
         * Amount in cents that is due for this order.
         */
        public readonly int $dueAmount,
        /**
         * Amount refunded in cents.
         */
        public readonly int $refundedAmount,
        /**
         * Sales tax refunded in cents.
         */
        public readonly int $refundedTaxAmount,
        public readonly string $currency,
        public readonly OrderBillingReason $billingReason,
        /**
         * The name of the customer that should appear on the invoice.
         */
        public readonly ?string $billingName,
        public readonly ?Address $billingAddress,
        /**
         * The invoice number associated with this order. `null` while the order is in `draft` status;
         * assigned at finalize.
         */
        public readonly ?string $invoiceNumber,
        /**
         * Whether an invoice has been generated for this order.
         */
        public readonly bool $isInvoiceGenerated,
        /**
         * The receipt number for this order. Set once the order is paid for organizations with
         * receipts enabled. When set, a downloadable receipt PDF can be obtained via the receipt
         * endpoint.
         */
        public readonly ?string $receiptNumber,
        public readonly string $customerId,
        public readonly ?string $productId,
        public readonly ?string $discountId,
        public readonly ?string $subscriptionId,
        public readonly ?string $checkoutId,
        /**
         * @var array<string, mixed>
         */
        public readonly array $metadata,
        /**
         * Platform fee amount in cents.
         */
        public readonly int $platformFeeAmount,
        /**
         * Currency of the platform fee.
         */
        public readonly ?string $platformFeeCurrency,
        public readonly OrderCustomer $customer,
        public readonly ?OrderProduct $product,
        /**
         * @var DiscountFixedOnceForeverDurationBase|DiscountFixedRepeatDurationBase|DiscountPercentageOnceForeverDurationBase|DiscountPercentageRepeatDurationBase|null
         */
        public readonly DiscountFixedOnceForeverDurationBase|DiscountFixedRepeatDurationBase|DiscountPercentageOnceForeverDurationBase|DiscountPercentageRepeatDurationBase|null $discount,
        public readonly ?OrderSubscription $subscription,
        /**
         * Line items composing the order.
         *
         * @var list<OrderItemSchema>
         */
        public readonly array $items,
        /**
         * A summary description of the order.
         */
        public readonly string $description,
        /**
         * Amount in cents that can still be refunded (net, before taxes). Accounts for any applied
         * customer balance and previous refunds.
         */
        public readonly int $refundableAmount,
        /**
         * Sales tax in cents that would be refunded if the full refundable amount is refunded.
         */
        public readonly int $refundableTaxAmount,
        /**
         * Number of seats purchased (for seat-based one-time orders).
         */
        public readonly ?int $seats = null,
        /**
         * When the next automatic payment retry is scheduled. `null` if the order is not in dunning or
         * all retries have been exhausted.
         */
        public readonly ?CarbonImmutable $nextPaymentAttemptAt = null,
        /**
         * Key-value object storing custom field values.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $customFieldData = null,
    ) {}
}
