<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * An order line item.
 */
#[MapName(SnakeCaseMapper::class)]
class OrderItemSchema extends Data
{
    public function __construct(
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * Description of the line item charge.
         */
        public readonly string $label,
        /**
         * Amount in cents, before discounts and taxes.
         */
        public readonly int $amount,
        /**
         * Sales tax amount in cents.
         */
        public readonly int $taxAmount,
        /**
         * Whether this charge is due to a proration.
         */
        public readonly bool $proration,
        /**
         * Associated price ID, if any.
         */
        public readonly ?string $productPriceId,
    ) {}
}
