<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\OrganizationStatus;
use Danestves\LaravelPolar\Enums\SubscriptionProrationBehavior;
use Danestves\LaravelPolar\Enums\TaxBehaviorOption;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class Organization extends PolarData
{
    public function __construct(
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * Organization name shown in checkout, customer portal, emails etc.
         */
        public readonly string $name,
        /**
         * Unique organization slug in checkout, customer portal and credit card statements.
         */
        public readonly string $slug,
        /**
         * Avatar URL shown in checkout, customer portal, emails etc.
         */
        public readonly ?string $avatarUrl,
        /**
         * Proration behavior applied when customer updates their subscription from the portal.
         */
        public readonly SubscriptionProrationBehavior $prorationBehavior,
        /**
         * Whether customers can update their subscriptions from the customer portal.
         */
        public readonly bool $allowCustomerUpdates,
        /**
         * Public support email.
         */
        public readonly ?string $email,
        /**
         * Official website of the organization.
         */
        public readonly ?string $website,
        /**
         * Links to social profiles.
         *
         * @var list<OrganizationSocialLink>
         */
        public readonly array $socials,
        /**
         * Current organization status
         */
        public readonly OrganizationStatus $status,
        /**
         * When the business details were submitted for review.
         */
        public readonly ?CarbonImmutable $detailsSubmittedAt,
        /**
         * When Polar requested that the organization review and resubmit its onboarding information,
         * if applicable.
         */
        public readonly ?CarbonImmutable $onboardingResubmissionRequestedAt,
        /**
         * Whether members must access this organization through its SSO connection.
         */
        public readonly bool $ssoEnforced,
        /**
         * Default presentment currency. Used as fallback in checkout and customer portal, if the
         * customer's local currency is not available.
         */
        public readonly string $defaultPresentmentCurrency,
        /**
         * Default tax behavior applied on products.
         */
        public readonly TaxBehaviorOption $defaultTaxBehavior,
        /**
         * Organization feature settings
         */
        public readonly ?OrganizationFeatureSettings $featureSettings,
        /**
         * Settings related to subscriptions management
         */
        public readonly OrganizationSubscriptionSettings $subscriptionSettings,
        /**
         * Settings related to customer emails
         */
        public readonly OrganizationCustomerEmailSettings $customerEmailSettings,
        /**
         * Settings related to the customer portal
         */
        public readonly OrganizationCustomerPortalSettings $customerPortalSettings,
        /**
         * Settings related to disputes
         */
        public readonly OrganizationDisputeSettings $disputeSettings,
        /**
         * Hosts allowed to embed this organization's checkout. An entry is a host and an optional
         * port, without a scheme: HTTPS is always allowed, and HTTP too for local hosts —
         * `localhost`, any `.localhost` or `.local` name, and loopback or private addresses.
         * `*.example.com` matches any subdomain, but not `example.com` itself. An app origin such as
         * `chrome-extension://abcdef` carries its scheme, having no host to match on.
         *
         * @var list<string>
         */
        public readonly array $embedHosts,
        /**
         * Whether an embedding page's origin must match `embed_hosts`. Organizations that have not
         * configured a list yet embed unchecked until the allowlist is enforced for everyone.
         */
        public readonly bool $embedHostsEnforced,
        /**
         * ID of the transactions account.
         */
        public readonly ?string $accountId,
        /**
         * ID of the payout account.
         */
        public readonly ?string $payoutAccountId,
        /**
         * Capabilities currently granted to the organization.
         */
        public readonly OrganizationCapabilities $capabilities,
        /**
         * Two-letter country code (ISO 3166-1 alpha-2).
         */
        public readonly ?string $country = null,
    ) {}
}
