<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class OrganizationFeatureSettings extends PolarData
{
    public function __construct(
        /**
         * If this organization has issue funding enabled
         */
        public readonly ?bool $issueFundingEnabled = null,
        /**
         * If this organization has seat-based pricing enabled
         */
        public readonly ?bool $seatBasedPricingEnabled = null,
        /**
         * If this organization has Wallets enabled
         */
        public readonly ?bool $walletsEnabled = null,
        /**
         * If this organization has the Member model enabled
         */
        public readonly ?bool $memberModelEnabled = null,
        /**
         * If this organization has checkout localization enabled
         */
        public readonly ?bool $checkoutLocalizationEnabled = null,
        /**
         * Ordered list of metric slugs shown on the dashboard overview.
         *
         * @var list<string>|null
         */
        public readonly ?array $overviewMetrics = null,
        /**
         * If this organization has access to reset proration behavior.
         */
        public readonly ?bool $resetProrationBehaviorEnabled = null,
        /**
         * If this organization can create and finalize draft orders via the API (off-session charges
         * against a saved payment method).
         */
        public readonly ?bool $offSessionChargesEnabled = null,
        /**
         * Enables the slack shared channel benefit
         */
        public readonly ?bool $slackBenefitEnabled = null,
        /**
         * If this organization has preview access to new features enabled
         */
        public readonly ?bool $previewAccessEnabled = null,
        /**
         * If this organization has the disputes dashboard enabled
         */
        public readonly ?bool $disputesEnabled = null,
        /**
         * If this organization has single sign-on configuration enabled
         */
        public readonly ?bool $ssoEnabled = null,
        /**
         * If this organization can set a threshold below which Polar concedes disputes on its behalf.
         * Requires `disputes_enabled`.
         */
        public readonly ?bool $disputeAutoAcceptEnabled = null,
        /**
         * If this organization has the split product navigation (Billing / Compass / Customers)
         * enabled in the dashboard
         */
        public readonly ?bool $compassEnabled = null,
        /**
         * If this organization can migrate its billing from another provider (e.g. Stripe) to Polar.
         */
        public readonly ?bool $merchantMigrationEnabled = null,
    ) {}
}
