<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class OrganizationCapabilities extends Data
{
    public function __construct(
        /**
         * Whether the organization can accept new checkout payments.
         */
        public readonly bool $checkoutPayments,
        /**
         * Whether the organization can process subscription renewals.
         */
        public readonly bool $subscriptionRenewals,
        /**
         * Whether the organization can withdraw its balance.
         */
        public readonly bool $payouts,
        /**
         * Whether the organization can issue refunds.
         */
        public readonly bool $refunds,
        /**
         * Whether the organization can access the API.
         */
        public readonly bool $apiAccess,
        /**
         * Whether the organization can access the dashboard.
         */
        public readonly bool $dashboardAccess,
    ) {}
}
