<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\OrganizationSocialPlatforms;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class OrganizationSocialLink extends Data
{
    public function __construct(
        /**
         * The social platform of the URL
         */
        public readonly OrganizationSocialPlatforms $platform,
        /**
         * The URL to the organization profile
         */
        public readonly string $url,
    ) {}
}
