<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * `auto_accept_below_amount` is in Polar's settlement currency (USD).
 */
#[MapName(SnakeCaseMapper::class)]
class OrganizationDisputeSettings extends Data
{
    public function __construct(
        public readonly ?int $autoAcceptBelowAmount,
    ) {}
}
