<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class OrganizationCustomerEmailSettings extends Data
{
    public function __construct(
        public readonly bool $orderConfirmation,
        public readonly bool $paymentMethodExpirationReminder,
        public readonly bool $subscriptionCancellation,
        public readonly bool $subscriptionConfirmation,
        public readonly bool $subscriptionCycled,
        public readonly bool $subscriptionCycledAfterTrial,
        public readonly bool $subscriptionPastDue,
        public readonly bool $subscriptionPaused,
        public readonly bool $subscriptionResumed,
        public readonly bool $subscriptionRenewalReminder,
        public readonly bool $subscriptionRevoked,
        public readonly bool $subscriptionTrialConversionReminder,
        public readonly bool $subscriptionUncanceled,
        public readonly bool $subscriptionUpdated,
    ) {}
}
