<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class OrganizationSubscriptionSettings extends Data
{
    public function __construct(
        public readonly bool $allowMultipleSubscriptions,
        public readonly string $prorationBehavior,
        public readonly int $benefitRevocationGracePeriod,
        public readonly bool $preventTrialAbuse,
        public readonly bool $allowCustomerUpdates,
    ) {}
}
