<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class PaymentMethodCardMetadata extends PolarData
{
    public function __construct(
        public readonly string $brand,
        public readonly string $last4,
        public readonly int $expMonth,
        public readonly int $expYear,
        public readonly ?string $wallet = null,
    ) {}
}
