<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Pending update to be applied to a subscription at the beginning of the next period.
 */
#[MapName(SnakeCaseMapper::class)]
class PendingSubscriptionUpdate extends PolarData
{
    public function __construct(
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * The date and time when the subscription update will be applied.
         */
        public readonly CarbonImmutable $appliesAt,
        /**
         * ID of the new product to apply to the subscription. If `null`, the product won't be changed.
         */
        public readonly ?string $productId,
        /**
         * Number of seats to apply to the subscription. If `null`, the number of seats won't be
         * changed.
         */
        public readonly ?int $seats,
    ) {}
}
