<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A fixed price for a product.
 */
#[MapName(SnakeCaseMapper::class)]
class ProductPriceFixed extends ProductPrice
{
    /**
     * The price in cents.
     */
    public int $priceAmount;
}
