<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A pricing tier for seat-based pricing.
 */
#[MapName(SnakeCaseMapper::class)]
class ProductPriceSeatTier extends Data
{
    public function __construct(
        /**
         * Minimum number of seats (inclusive)
         */
        public readonly int $minSeats,
        /**
         * Price per seat in cents for this tier
         */
        public readonly int $pricePerSeat,
        /**
         * Maximum number of seats (inclusive). None for unlimited.
         */
        public readonly ?int $maxSeats = null,
    ) {}
}
