<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\MeterUnit;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A meter associated to a metered price.
 */
#[MapName(SnakeCaseMapper::class)]
class ProductPriceMeter extends Data
{
    public function __construct(
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * The name of the meter.
         */
        public readonly string $name,
        /**
         * The unit of the meter.
         */
        public readonly MeterUnit $unit,
        /**
         * The label for the custom unit.
         */
        public readonly ?string $customLabel,
        /**
         * The multiplier to convert from base unit to display scale.
         */
        public readonly ?int $customMultiplier,
    ) {}
}
