<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\ProductVisibility;
use Danestves\LaravelPolar\Enums\RecurringInterval;
use Danestves\LaravelPolar\Enums\TrialInterval;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A product.
 */
#[MapName(SnakeCaseMapper::class)]
class Product extends Data
{
    public function __construct(
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The interval unit for the trial period.
         */
        public readonly ?TrialInterval $trialInterval,
        /**
         * The number of interval units for the trial period.
         */
        public readonly ?int $trialIntervalCount,
        /**
         * The name of the product.
         */
        public readonly string $name,
        /**
         * The description of the product.
         */
        public readonly ?string $description,
        /**
         * The visibility of the product.
         */
        public readonly ProductVisibility $visibility,
        /**
         * The recurring interval of the product. If `None`, the product is a one-time purchase.
         */
        public readonly ?RecurringInterval $recurringInterval,
        /**
         * Number of interval units of the subscription. If this is set to 1 the charge will happen
         * every interval (e.g. every month), if set to 2 it will be every other month, and so on. None
         * for one-time products.
         */
        public readonly ?int $recurringIntervalCount,
        /**
         * The meter cycle of the product, independent of the billing interval. If `None`, metered
         * concerns follow the billing interval.
         */
        public readonly ?RecurringInterval $meterInterval,
        /**
         * Number of meter interval units. None when no meter cycle is set.
         */
        public readonly ?int $meterIntervalCount,
        /**
         * Whether the product is a subscription.
         */
        public readonly bool $isRecurring,
        /**
         * Whether the product is archived and no longer available.
         */
        public readonly bool $isArchived,
        /**
         * The ID of the organization owning the product.
         */
        public readonly string $organizationId,
        /**
         * @var array<string, mixed>
         */
        public readonly array $metadata,
        /**
         * List of prices for this product.
         *
         * @var list<LegacyRecurringProductPrice|ProductPrice>
         */
        public readonly array $prices,
        /**
         * List of benefits granted by the product.
         *
         * @var list<Benefit>
         */
        public readonly array $benefits,
        /**
         * List of medias associated to the product.
         *
         * @var list<ProductMediaFileRead>
         */
        public readonly array $medias,
        /**
         * List of custom fields attached to the product.
         *
         * @var list<AttachedCustomField>
         */
        public readonly array $attachedCustomFields,
    ) {}
}
