<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\SeatTierType;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * List of pricing tiers for seat-based pricing.
 *
 * The minimum and maximum seat limits are derived from the tiers:
 * - minimum_seats = first tier's min_seats
 * - maximum_seats = last tier's max_seats (None for unlimited)
 */
#[MapName(SnakeCaseMapper::class)]
class ProductPriceSeatTiersOutput extends PolarData
{
    public function __construct(
        /**
         * List of pricing tiers
         *
         * @var list<ProductPriceSeatTier>
         */
        public readonly array $tiers,
        /**
         * Minimum number of seats required for purchase, derived from first tier.
         */
        public readonly int $minimumSeats,
        /**
         * Maximum number of seats allowed for purchase, derived from last tier. None for unlimited.
         */
        public readonly ?int $maximumSeats,
        /**
         * How tiers are applied. 'volume' prices all seats at the matching tier's rate. 'graduated'
         * prices each tier's range independently.
         */
        public readonly ?SeatTierType $seatTierType = null,
    ) {}
}
