<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A pay-what-you-want price for a product.
 */
#[MapName(SnakeCaseMapper::class)]
class ProductPriceCustom extends ProductPrice
{
    /**
     * The minimum amount the customer can pay. If 0, the price is 'free or pay what you want'.
     */
    public int $minimumAmount;

    /**
     * The maximum amount the customer can pay.
     */
    public ?int $maximumAmount;

    /**
     * The initial amount shown to the customer.
     */
    public ?int $presetAmount;
}
