<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\PresentmentCurrency;
use Danestves\LaravelPolar\Enums\TaxBehaviorOption;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema to create a metered price with a fixed unit price.
 */
#[MapName(SnakeCaseMapper::class)]
class ProductPriceMeteredUnitCreate extends Data
{
    public function __construct(
        /**
         * The ID of the meter associated to the price.
         */
        public readonly string $meterId,
        /**
         * The price per unit in cents. Supports up to 12 decimal places.
         *
         * @var float|string
         */
        public readonly float|string $unitAmount,
        public readonly string $amountType = 'metered_unit',
        /**
         * The currency in which the customer will be charged.
         */
        public readonly ?PresentmentCurrency $priceCurrency = null,
        /**
         * The tax behavior of the price. If not set, it will default to the organization's default tax
         * behavior.
         */
        public readonly ?TaxBehaviorOption $taxBehavior = null,
        /**
         * Optional maximum amount in cents that can be charged, regardless of the number of units
         * consumed.
         */
        public readonly ?int $capAmount = null,
    ) {}
}
