<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\PresentmentCurrency;
use Danestves\LaravelPolar\Enums\TaxBehaviorOption;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Schema to create a seat-based price with volume-based tiers.
 */
#[MapName(SnakeCaseMapper::class)]
class ProductPriceSeatBasedCreate extends Data
{
    public function __construct(
        /**
         * Tiered pricing based on seat quantity
         */
        public readonly ProductPriceSeatTiersInput $seatTiers,
        public readonly string $amountType = 'seat_based',
        /**
         * The currency in which the customer will be charged.
         */
        public readonly ?PresentmentCurrency $priceCurrency = null,
        /**
         * The tax behavior of the price. If not set, it will default to the organization's default tax
         * behavior.
         */
        public readonly ?TaxBehaviorOption $taxBehavior = null,
    ) {}
}
