<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * File to be used as a product media file.
 */
#[MapName(SnakeCaseMapper::class)]
class ProductMediaFileRead extends FileRead
{
    public string $publicUrl;
}
