<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * A metered, usage-based, price for a product, with a fixed unit price.
 */
#[MapName(SnakeCaseMapper::class)]
class ProductPriceMeteredUnit extends ProductPrice
{
    /**
     * The price per unit in cents.
     */
    public string $unitAmount;

    /**
     * The maximum amount in cents that can be charged, regardless of the number of units consumed.
     */
    public ?int $capAmount;

    /**
     * The ID of the meter associated to the price.
     */
    public string $meterId;

    /**
     * The meter associated to the price.
     */
    public ProductPriceMeter $meter;
}
