<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\DisputeStatus;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Dispute associated with a refund,
 * in case we prevented a dispute by issuing a refund.
 */
#[MapName(SnakeCaseMapper::class)]
class RefundDispute extends Data
{
    public function __construct(
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * Status of the dispute. `prevented` means we issued a refund before the dispute was
         * escalated, avoiding any fees.
         */
        public readonly DisputeStatus $status,
        /**
         * Whether the dispute has been resolved (won or lost).
         */
        public readonly bool $resolved,
        /**
         * Whether the dispute is closed (prevented, won, or lost).
         */
        public readonly bool $closed,
        /**
         * Amount in cents disputed.
         */
        public readonly int $amount,
        /**
         * Tax amount in cents disputed.
         */
        public readonly int $taxAmount,
        /**
         * Currency code of the dispute.
         */
        public readonly string $currency,
        /**
         * The reason for the dispute as reported by the card network (e.g. `fraudulent`,
         * `product_not_received`). `None` until the processor reports it.
         */
        public readonly ?string $reason,
        /**
         * Deadline to submit evidence in response to the dispute. `None` when no response is required.
         */
        public readonly ?CarbonImmutable $evidenceDueBy,
        /**
         * Whether the evidence submission deadline has passed.
         */
        public readonly bool $pastDue,
        /**
         * The ID of the order associated with the dispute.
         */
        public readonly string $orderId,
        /**
         * The ID of the payment associated with the dispute.
         */
        public readonly string $paymentId,
    ) {}
}
