<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\RefundCreateReason;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class RefundCreate extends PolarData
{
    public function __construct(
        public readonly string $orderId,
        /**
         * Reason for the refund.
         */
        public readonly RefundCreateReason $reason,
        /**
         * Amount to refund in cents. Minimum is 1.
         */
        public readonly int $amount,
        /**
         * Key-value object allowing you to store additional information.
         *
         * The key must be a string with a maximum length of **40 characters**.
         * The value must be either:
         *
         * * A string with a maximum length of **500 characters**
         * * An integer
         * * A floating-point number
         * * A boolean
         *
         * You can store up to **50 key-value pairs**.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $metadata = null,
        /**
         * An internal comment about the refund.
         */
        public readonly ?string $comment = null,
        /**
         * Should this refund trigger the associated customer benefits to be revoked?
         *
         * **Note:**
         * Only allowed in case the `order` is a one-time purchase.
         * Subscriptions automatically revoke customer benefits once the
         * subscription itself is revoked, i.e fully canceled.
         */
        public readonly ?bool $revokeBenefits = null,
    ) {}
}
