<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\RefundReason;
use Danestves\LaravelPolar\Enums\RefundStatus;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class Refund extends Data
{
    public function __construct(
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * @var array<string, mixed>
         */
        public readonly array $metadata,
        public readonly RefundStatus $status,
        public readonly RefundReason $reason,
        public readonly int $amount,
        public readonly int $taxAmount,
        public readonly string $currency,
        public readonly string $organizationId,
        public readonly string $orderId,
        public readonly ?string $subscriptionId,
        public readonly string $customerId,
        public readonly bool $revokeBenefits,
        public readonly ?RefundDispute $dispute,
    ) {}
}
