<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class SeatAssign extends Data
{
    public function __construct(
        /**
         * Subscription ID. Required if neither order_id nor checkout_id is provided.
         */
        public readonly ?string $subscriptionId = null,
        /**
         * Order ID for one-time purchases. Required if subscription_id is not provided.
         */
        public readonly ?string $orderId = null,
        /**
         * Email of the customer to assign the seat to
         */
        public readonly ?string $email = null,
        /**
         * External customer ID for the seat assignment
         */
        public readonly ?string $externalCustomerId = null,
        /**
         * Customer ID for the seat assignment
         */
        public readonly ?string $customerId = null,
        /**
         * External member ID for the seat assignment. Can be used alone (lookup existing member) or
         * with email (create/validate member).
         */
        public readonly ?string $externalMemberId = null,
        /**
         * Member ID for the seat assignment.
         */
        public readonly ?string $memberId = null,
        /**
         * Additional metadata for the seat (max 10 keys, 1KB total)
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $metadata = null,
        /**
         * If true, the seat will be immediately claimed without sending an invitation email. API-only
         * feature.
         */
        public readonly ?bool $immediateClaim = null,
    ) {}
}
