<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class SeatsList extends Data
{
    public function __construct(
        /**
         * List of seats
         *
         * @var list<CustomerSeat>
         */
        public readonly array $seats,
        /**
         * Number of available seats
         */
        public readonly int $availableSeats,
        /**
         * Total number of seats for the subscription
         */
        public readonly int $totalSeats,
    ) {}
}
