<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\SubscriptionProrationBehavior;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class SubscriptionUpdateBase extends PolarData implements SubscriptionUpdate
{
    public function __construct(
        /**
         * Update subscription to another product.
         */
        public readonly ?string $productId = null,
        /**
         * Determine how to handle the proration billing. If not provided, will use the default
         * organization setting.
         */
        public readonly ?SubscriptionProrationBehavior $prorationBehavior = null,
        /**
         * Update the subscription to apply a new discount. If set to `null`, the discount will be
         * removed. The change will be applied on the next billing cycle.
         */
        public readonly ?string $discountId = null,
        /**
         * Set or extend the trial period of the subscription. If set to `now`, the trial will end
         * immediately.
         *
         * @var CarbonImmutable|string|null
         */
        public readonly CarbonImmutable|string|null $trialEnd = null,
    ) {}
}
