<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Enums\CustomerCancellationReason;
use Danestves\LaravelPolar\Enums\RecurringInterval;
use Danestves\LaravelPolar\Enums\SubscriptionStatus;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class Subscription extends Data
{
    public function __construct(
        /**
         * Creation timestamp of the object.
         */
        public readonly CarbonImmutable $createdAt,
        /**
         * Last modification timestamp of the object.
         */
        public readonly ?CarbonImmutable $modifiedAt,
        /**
         * The ID of the object.
         */
        public readonly string $id,
        /**
         * The amount of the subscription.
         */
        public readonly int $amount,
        /**
         * The currency of the subscription.
         */
        public readonly string $currency,
        /**
         * The interval at which the subscription recurs.
         */
        public readonly RecurringInterval $recurringInterval,
        /**
         * Number of interval units of the subscription. If this is set to 1 the charge will happen
         * every interval (e.g. every month), if set to 2 it will be every other month, and so on.
         */
        public readonly int $recurringIntervalCount,
        /**
         * The status of the subscription.
         */
        public readonly SubscriptionStatus $status,
        /**
         * The start timestamp of the current billing period.
         */
        public readonly CarbonImmutable $currentPeriodStart,
        /**
         * The end timestamp of the current billing period.
         */
        public readonly CarbonImmutable $currentPeriodEnd,
        /**
         * The start timestamp of the current meter period, if the product has a meter cycle set.
         * Metered credits are granted and overage is settled on this cadence.
         */
        public readonly ?CarbonImmutable $currentMeterPeriodStart,
        /**
         * The end timestamp of the current meter period, if the product has a meter cycle set. This is
         * when credits next renew.
         */
        public readonly ?CarbonImmutable $currentMeterPeriodEnd,
        /**
         * The start timestamp of the trial period, if any.
         */
        public readonly ?CarbonImmutable $trialStart,
        /**
         * The end timestamp of the trial period, if any.
         */
        public readonly ?CarbonImmutable $trialEnd,
        /**
         * Whether the subscription will be canceled at the end of the current period.
         */
        public readonly bool $cancelAtPeriodEnd,
        /**
         * The timestamp when the subscription was canceled. The subscription might still be active if
         * `cancel_at_period_end` is `true`.
         */
        public readonly ?CarbonImmutable $canceledAt,
        /**
         * The timestamp when the subscription started.
         */
        public readonly ?CarbonImmutable $startedAt,
        /**
         * The timestamp when the subscription will end.
         */
        public readonly ?CarbonImmutable $endsAt,
        /**
         * The timestamp when the subscription ended.
         */
        public readonly ?CarbonImmutable $endedAt,
        /**
         * Whether the subscription will be paused at the end of the current period.
         */
        public readonly bool $pauseAtPeriodEnd,
        /**
         * The timestamp when the subscription was paused.
         */
        public readonly ?CarbonImmutable $pausedAt,
        /**
         * The timestamp when a paused subscription is scheduled to automatically resume, if set.
         */
        public readonly ?CarbonImmutable $resumesAt,
        /**
         * The ID of the subscribed customer.
         */
        public readonly string $customerId,
        /**
         * The ID of the subscribed product.
         */
        public readonly string $productId,
        /**
         * The ID of the applied discount, if any.
         */
        public readonly ?string $discountId,
        public readonly ?string $checkoutId,
        public readonly ?CustomerCancellationReason $customerCancellationReason,
        public readonly ?string $customerCancellationComment,
        /**
         * @var array<string, mixed>
         */
        public readonly array $metadata,
        public readonly SubscriptionCustomer $customer,
        public readonly Product $product,
        /**
         * @var DiscountFixedOnceForeverDurationBase|DiscountFixedRepeatDurationBase|DiscountPercentageOnceForeverDurationBase|DiscountPercentageRepeatDurationBase|null
         */
        public readonly DiscountFixedOnceForeverDurationBase|DiscountFixedRepeatDurationBase|DiscountPercentageOnceForeverDurationBase|DiscountPercentageRepeatDurationBase|null $discount,
        /**
         * List of enabled prices for the subscription.
         *
         * @var list<LegacyRecurringProductPrice|ProductPrice>
         */
        public readonly array $prices,
        /**
         * List of meters associated with the subscription.
         *
         * @var list<SubscriptionMeter>
         */
        public readonly array $meters,
        /**
         * Pending subscription update that will be applied at the beginning of the next period. If
         * `null`, there is no pending update.
         */
        public readonly ?PendingSubscriptionUpdate $pendingUpdate,
        /**
         * The timestamp when the subscription entered `past_due` status.
         */
        public readonly ?CarbonImmutable $pastDueAt = null,
        /**
         * The number of seats for seat-based subscriptions. None for non-seat subscriptions.
         */
        public readonly ?int $seats = null,
        /**
         * Key-value object storing custom field values.
         *
         * @var array<string, mixed>|null
         */
        public readonly ?array $customFieldData = null,
    ) {}
}
