<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class SubscriptionUpdateBillingPeriod extends Data implements SubscriptionUpdate
{
    public function __construct(
        /**
         * Set a new date for the end of the current billing period. The subscription will renew on
         * this date. The new date can be earlier or later than the current period end, as long as it's
         * in the future.
         *
         * It is not possible to update the current billing period on a canceled subscription.
         */
        public readonly CarbonImmutable $currentBillingPeriodEnd,
    ) {}
}
