<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\CustomerCancellationReason;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class SubscriptionCancel extends Data implements SubscriptionUpdate
{
    public function __construct(
        /**
         * Cancel an active subscription once the current period ends.
         *
         * Or uncancel a subscription currently set to be revoked at period end.
         */
        public readonly bool $cancelAtPeriodEnd,
        /**
         * Customer reason for cancellation.
         *
         * Helpful to monitor reasons behind churn for future improvements.
         *
         * Only set this in case your own service is requesting the reason from the
         * customer. Or you know based on direct conversations, i.e support, with
         * the customer.
         *
         * * `too_expensive`: Too expensive for the customer.
         * * `missing_features`: Customer is missing certain features.
         * * `switched_service`: Customer switched to another service.
         * * `unused`: Customer is not using it enough.
         * * `customer_service`: Customer is not satisfied with the customer service.
         * * `low_quality`: Customer is unhappy with the quality.
         * * `too_complex`: Customer considers the service too complicated.
         * * `other`: Other reason(s).
         */
        public readonly ?CustomerCancellationReason $customerCancellationReason = null,
        /**
         * Customer feedback and why they decided to cancel.
         *
         * **IMPORTANT:**
         * Do not use this to store internal notes! It's intended to be input
         * from the customer and is therefore also available in their Polar
         * purchases library.
         *
         * Only set this in case your own service is requesting the reason from the
         * customer. Or you copy a message directly from a customer
         * conversation, i.e support.
         */
        public readonly ?string $customerCancellationComment = null,
    ) {}
}
