<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class SubscriptionUpdateClear extends PolarData implements SubscriptionUpdate
{
    public function __construct(
        /**
         * Clear the pending subscription update. Set to null to remove scheduled changes.
         */
        public readonly mixed $pendingUpdate,
    ) {}
}
