<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class SubscriptionPause extends PolarData implements SubscriptionUpdate
{
    public function __construct(
        /**
         * Pause an active subscription at the end of the current period.
         *
         * Or cancel a scheduled pause on a subscription set to be paused at
         * period end.
         */
        public readonly bool $pauseAtPeriodEnd,
        /**
         * Date at which the paused subscription should automatically resume.
         *
         * If not set, the subscription stays paused until it is resumed manually.
         * Must be after the current period end.
         */
        public readonly ?CarbonImmutable $resumesAt = null,
    ) {}
}
