<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class SubscriptionResume extends PolarData implements SubscriptionUpdate
{
    public function __construct(
        /**
         * Resume a paused subscription immediately, starting a new billing period and charging the
         * customer.
         */
        public readonly bool $resume = true,
    ) {}
}
