<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Danestves\LaravelPolar\Enums\SubscriptionProrationBehavior;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

#[MapName(SnakeCaseMapper::class)]
class SubscriptionUpdateSeats extends Data implements SubscriptionUpdate
{
    public function __construct(
        /**
         * Update the number of seats for this subscription.
         */
        public readonly int $seats,
        /**
         * Determine how to handle the proration billing. If not provided, will use the default
         * organization setting.
         */
        public readonly ?SubscriptionProrationBehavior $prorationBehavior = null,
    ) {}
}
