<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * File attached to a support case (private; fetched via presigned URL).
 */
#[MapName(SnakeCaseMapper::class)]
class SupportCaseAttachmentFileRead extends FileRead {}
