<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Sent when a customer is updated.
 *
 * This event is fired when the customer details are updated.
 *
 * If you want to be notified when a customer subscription or benefit state changes, you should
 * listen to the `customer_state_changed` event.
 *
 * **Discord & Slack support:** Basic
 */
#[MapName(SnakeCaseMapper::class)]
class WebhookCustomerUpdatedPayload extends Data
{
    public function __construct(
        public readonly CarbonImmutable $timestamp,
        public readonly Customer $data,
        public readonly string $type = 'customer.updated',
    ) {}
}
