<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Sent when a new subscription is created.
 *
 * When this event occurs, the subscription `status` might not be `active` yet, as we can still
 * have to wait for the first payment to be processed.
 *
 * **Discord & Slack support:** Full
 */
#[MapName(SnakeCaseMapper::class)]
class WebhookSubscriptionCreatedPayload extends PolarData
{
    public function __construct(
        public readonly CarbonImmutable $timestamp,
        public readonly Subscription $data,
        public readonly string $type = 'subscription.created',
    ) {}
}
