<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Sent when a new benefit is created.
 *
 * **Discord & Slack support:** Basic
 */
#[MapName(SnakeCaseMapper::class)]
class WebhookBenefitCreatedPayload extends Data
{
    public function __construct(
        public readonly CarbonImmutable $timestamp,
        public readonly Benefit $data,
        public readonly string $type = 'benefit.created',
    ) {}
}
