<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Sent when a subscription is revoked and the user loses access immediately.
 * Happens when the subscription is canceled or payment retries are exhausted (status becomes
 * `unpaid`).
 *
 * For payment failures that can still be recovered, see `subscription.past_due`.
 *
 * **Discord & Slack support:** Full
 */
#[MapName(SnakeCaseMapper::class)]
class WebhookSubscriptionRevokedPayload extends Data
{
    public function __construct(
        public readonly CarbonImmutable $timestamp,
        public readonly Subscription $data,
        public readonly string $type = 'subscription.revoked',
    ) {}
}
