<?php

// This file is generated by tools/generate-data.php. Do not edit by hand.

declare(strict_types=1);

namespace Danestves\LaravelPolar\Data;

use Carbon\CarbonImmutable;
use Danestves\LaravelPolar\Support\PolarData;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Sent when a benefit grant is updated.
 *
 * **Discord & Slack support:** Basic
 */
#[MapName(SnakeCaseMapper::class)]
class WebhookBenefitGrantUpdatedPayload extends PolarData
{
    public function __construct(
        public readonly CarbonImmutable $timestamp,
        public readonly BenefitGrantWebhook $data,
        public readonly string $type = 'benefit_grant.updated',
    ) {}
}
